import './components';
import { TetherIoClient } from './client';
import { CatalogEntry, FunctionEntry, ValueType } from './protocol';
import './style.css';

class TetherApp extends HTMLElement {
  private readonly client = new TetherIoClient();
  private signals: CatalogEntry[] = [];
  private params: CatalogEntry[] = [];
  private active?: CatalogEntry;
  private activeKind: 'param' | 'signal' = 'signal';
  private functions: FunctionEntry[] = [];
  connectedCallback(): void { this.render(); this.bind(); }
  private render(): void { this.innerHTML = `<main class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">T</span><div><strong>Tether IO</strong><small>Realtime control cockpit</small></div></div><div class="connection"><input id="url" value="ws://127.0.0.1:8080/tether-io" aria-label="WebSocket URL"><button id="connect">Connect</button><span id="status" class="status">Offline</span></div></header><section class="hero"><div><p class="eyebrow">EtherCAT observability</p><h1>See the machine breathe.</h1><p class="lede">Explore live parameters, signals, functions and PDO telemetry through one calm, glassy control surface.</p></div><div class="hero-orb"><span>1 kHz</span><small>stream-ready</small></div></section><section class="workspace"><aside class="panel catalog-panel"><div class="panel-title"><div><span class="eyebrow">Catalog</span><h2>Everything at hand</h2></div><span id="catalog-count" class="badge">0</span></div><nav class="tabs"><button class="tab active" data-tab="signals">Signals</button><button class="tab" data-tab="params">Parameters</button><button class="tab" data-tab="functions">Functions</button></nav><tether-catalog id="catalog"></tether-catalog></aside><section class="content"><div class="toolbar panel"><div><span class="eyebrow">Live monitor</span><h2 id="selection-title">Select a signal to inspect</h2></div><div class="actions"><button id="read">Read once</button><button id="stream" class="primary">Start stream</button></div></div><div class="metrics"><article class="metric panel"><small>Connection</small><strong id="metric-connection">Offline</strong><span>WebSocket binary</span></article><article class="metric panel"><small>Selected points</small><strong id="metric-points">0</strong><span>ring-buffered locally</span></article><article class="metric panel"><small>Transport</small><strong>SLIP / IO v5</strong><span>bounded frames</span></article></div><section class="scope panel"><div class="scope-head"><div><span class="eyebrow">Oscilloscope</span><h2>Signal trace</h2></div><span class="live-dot">● LIVE</span></div><tether-scope id="scope"></tether-scope></section><section class="value-grid" id="value-grid"></section><section class="panel function-panel"><div class="panel-title"><div><span class="eyebrow">RPC surface</span><h2>Functions</h2></div></div><tether-function-list id="functions"></tether-function-list></section></section></section><footer><span>Static TypeScript web components</span><span>Designed for loss-tolerant realtime telemetry</span></footer></main>`; }
  private bind(): void { const connect = this.querySelector<HTMLButtonElement>('#connect')!; connect.addEventListener('click', () => void this.connect()); this.querySelector<HTMLButtonElement>('#read')!.addEventListener('click', () => void this.readActive()); this.querySelector<HTMLButtonElement>('#stream')!.addEventListener('click', () => void this.toggleStream()); this.querySelectorAll<HTMLButtonElement>('.tab').forEach(tab => tab.addEventListener('click', () => void this.switchTab(tab.dataset.tab as 'signals' | 'params' | 'functions'))); this.querySelector('tether-catalog')?.addEventListener('read-entry', event => { const id = (event as CustomEvent<bigint>).detail; this.active = [...this.signals, ...this.params].find(entry => entry.id === id); void this.readActive(); }); this.client.addEventListener('connected', () => this.setStatus('Online', true)); this.client.addEventListener('disconnected', () => this.setStatus('Offline', false)); this.client.addEventListener('error-message', event => this.setStatus((event as CustomEvent<{ message?: string }>).detail.message ?? 'Protocol error', false)); this.client.addEventListener('stream', event => { const row = (event as CustomEvent).detail; this.querySelector<tetherScope>('tether-scope')?.push(row, this.active?.type ?? ValueType.F32); this.querySelector('#metric-points')!.textContent = String(row.values.length); }); }
  private async connect(): Promise<void> { const url = this.querySelector<HTMLInputElement>('#url')!.value; try { await this.client.connect(url); await this.switchTab('signals'); } catch (error) { this.setStatus(error instanceof Error ? error.message : 'Connection failed', false); } }
  private async switchTab(tab: 'signals' | 'params' | 'functions'): Promise<void> { this.querySelectorAll('.tab').forEach(item => item.classList.toggle('active', (item as HTMLElement).dataset.tab === tab)); if (tab === 'functions') { try { this.functions = await this.client.listFunctions(); (this.querySelector('#functions') as HTMLElement & { items: FunctionEntry[] }).items = this.functions; } catch (error) { this.setStatus(error instanceof Error ? error.message : 'Function catalog failed', false); } return; } this.activeKind = tab === 'params' ? 'param' : 'signal'; try { const entries = await this.client.list(tab); if (tab === 'signals') this.signals = entries; else this.params = entries; this.renderCatalog(entries); } catch (error) { this.setStatus(error instanceof Error ? error.message : 'Catalog failed', false); } }
  private renderCatalog(entries: CatalogEntry[]): void { const catalog = this.querySelector('tether-catalog') as HTMLElement & { items: CatalogEntry[]; selectedIds: bigint[] }; catalog.items = entries; this.querySelector('#catalog-count')!.textContent = String(entries.length); catalog.addEventListener('selection-change', () => { const selected = catalog.selectedIds; this.active = entries.find(entry => entry.id === selected[0]); this.querySelector('#selection-title')!.textContent = this.active?.name ?? 'Select a signal to inspect'; }); }
  private async readActive(): Promise<void> { if (!this.active) return; try { const card = document.createElement('tether-value-card') as HTMLElement & { model: { entry: CatalogEntry; client: TetherIoClient }; read: () => Promise<void> }; card.model = { entry: this.active, client: this.client }; this.querySelector('#value-grid')!.replaceChildren(card); await card.read(); } catch { this.setStatus('Read failed', false); } }
  private async toggleStream(): Promise<void> { if (!this.active || this.activeKind !== 'signal') return; const button = this.querySelector<HTMLButtonElement>('#stream')!; if (button.dataset.running) { await this.client.stopStream(); delete button.dataset.running; button.textContent = 'Start stream'; } else { await this.client.configureStream((this.querySelector('tether-catalog') as HTMLElement & { selectedIds: bigint[] }).selectedIds, 10, 1); await this.client.startStream(); button.dataset.running = '1'; button.textContent = 'Stop stream'; } }
  private setStatus(text: string, online: boolean): void { this.querySelector('#status')!.textContent = text; this.querySelector('#metric-connection')!.textContent = text; this.querySelector('#status')!.classList.toggle('online', online); }
}
customElements.define('tether-app', TetherApp);
type tetherScope = HTMLElement & { push: (row: unknown, type: ValueType) => void };
