/**
 * @file GCodeGenerator.cpp
 * @brief Implementation of G-code generation for test patterns
 */

#include "GCodeGenerator.hpp"
#include <fstream>
#include <algorithm>
#include <cmath>

namespace MotionReplanner {

//=============================================================================
// GCodeProgram Implementation
//=============================================================================

GCodeProgram::GCodeProgram(const GCodeOptions& opts)
    : opts_(opts), nextLineNumber_(opts.lineNumberIncrement) {}

void GCodeProgram::addBlock(const GCodeBlock& block) {
    GCodeBlock b = block;
    if (opts_.useLineNumbers && b.lineNumber < 0) {
        b.lineNumber = nextLineNumber_;
        nextLineNumber_ += opts_.lineNumberIncrement;
    }
    blocks_.push_back(b);
}

void GCodeProgram::addBlock(const std::string& line) {
    GCodeBlock block;
    block.comment = line;
    addBlock(block);
}

void GCodeProgram::addComment(const std::string& comment) {
    GCodeBlock block;
    block.comment = comment;
    blocks_.push_back(block);
}

void GCodeProgram::addBlankLine() {
    GCodeBlock block;
    blocks_.push_back(block);
}

void GCodeProgram::addProgramStart() {
    addComment("Program generated by MotionReplanner");
    
    if (opts_.useMetric) {
        addUnitsMetric();
    } else {
        addUnitsInch();
    }
    
    if (opts_.absoluteMode) {
        addAbsoluteMode();
    } else {
        addIncrementalMode();
    }
}

void GCodeProgram::addProgramEnd() {
    GCodeBlock block;
    block.mCode = "M30";
    block.comment = "End program";
    addBlock(block);
}

void GCodeProgram::addUnitsMetric() {
    GCodeBlock block;
    block.gCode = "G21";
    block.comment = "Metric units";
    addBlock(block);
}

void GCodeProgram::addUnitsInch() {
    GCodeBlock block;
    block.gCode = "G20";
    block.comment = "Inch units";
    addBlock(block);
}

void GCodeProgram::addAbsoluteMode() {
    GCodeBlock block;
    block.gCode = "G90";
    block.comment = "Absolute positioning";
    addBlock(block);
}

void GCodeProgram::addIncrementalMode() {
    GCodeBlock block;
    block.gCode = "G91";
    block.comment = "Incremental positioning";
    addBlock(block);
}

void GCodeProgram::addRapid(double x, double y, double z) {
    GCodeBlock block;
    block.gCode = "G0";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.position[2] = z; block.hasPosition[2] = true;
    addBlock(block);
    
    currentX_ = x; currentY_ = y; currentZ_ = z;
}

void GCodeProgram::addRapidXY(double x, double y) {
    GCodeBlock block;
    block.gCode = "G0";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    addBlock(block);
    
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addRapidZ(double z) {
    GCodeBlock block;
    block.gCode = "G0";
    block.position[2] = z; block.hasPosition[2] = true;
    addBlock(block);
    
    currentZ_ = z;
}

void GCodeProgram::addLinear(double x, double y, double z, double feedRate) {
    GCodeBlock block;
    block.gCode = "G1";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.position[2] = z; block.hasPosition[2] = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y; currentZ_ = z;
}

void GCodeProgram::addLinearXY(double x, double y, double feedRate) {
    GCodeBlock block;
    block.gCode = "G1";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addArcCW(double x, double y, double i, double j, double feedRate) {
    GCodeBlock block;
    block.gCode = "G2";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.i = i; block.j = j; block.hasIJK = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addArcCCW(double x, double y, double i, double j, double feedRate) {
    GCodeBlock block;
    block.gCode = "G3";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.i = i; block.j = j; block.hasIJK = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addArcCW_R(double x, double y, double r, double feedRate) {
    GCodeBlock block;
    block.gCode = "G2";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.r = r; block.hasR = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addArcCCW_R(double x, double y, double r, double feedRate) {
    GCodeBlock block;
    block.gCode = "G3";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.r = r; block.hasR = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addDwell(double seconds) {
    GCodeBlock block;
    block.gCode = "G4";
    // P parameter in seconds or milliseconds depending on dialect
    std::ostringstream ss;
    ss << "G4 P" << std::fixed << std::setprecision(3) << seconds;
    block.comment = "";
    addBlock(ss.str());
}

void GCodeProgram::addToolChange(int toolNumber) {
    GCodeBlock block;
    std::ostringstream ss;
    ss << "T" << toolNumber << " M6";
    addBlock(ss.str());
}

void GCodeProgram::addSpindleOn(double rpm, bool cw) {
    GCodeBlock block;
    block.mCode = cw ? "M3" : "M4";
    block.spindleSpeed = rpm;
    addBlock(block);
}

void GCodeProgram::addSpindleOff() {
    GCodeBlock block;
    block.mCode = "M5";
    addBlock(block);
}

void GCodeProgram::addCoolantOn() {
    GCodeBlock block;
    block.mCode = "M8";
    addBlock(block);
}

void GCodeProgram::addCoolantOff() {
    GCodeBlock block;
    block.mCode = "M9";
    addBlock(block);
}

void GCodeProgram::addFeedRate(double feedRate) {
    GCodeBlock block;
    block.feedRate = feedRate;
    addBlock(block);
    currentFeed_ = feedRate;
}

std::string GCodeProgram::toString() const {
    std::ostringstream ss;
    write(ss);
    return ss.str();
}

bool GCodeProgram::saveToFile(const std::string& filename) const {
    std::ofstream file(filename);
    if (!file.is_open()) return false;
    write(file);
    return file.good();
}

void GCodeProgram::write(std::ostream& out) const {
    for (const auto& block : blocks_) {
        std::string line = block.toString(opts_);
        if (!line.empty() || block.comment.empty()) {
            out << line << "\n";
        }
    }
}

double GCodeProgram::estimateDuration() const {
    double duration = 0.0;
    double lastX = 0, lastY = 0, lastZ = 0;
    double currentFeed = opts_.defaultFeedRate;
    
    for (const auto& block : blocks_) {
        double x = lastX, y = lastY, z = lastZ;
        
        if (block.hasPosition[0]) x = block.position[0];
        if (block.hasPosition[1]) y = block.position[1];
        if (block.hasPosition[2]) z = block.position[2];
        
        double dist = std::sqrt(
            (x - lastX) * (x - lastX) +
            (y - lastY) * (y - lastY) +
            (z - lastZ) * (z - lastZ)
        );
        
        double feed = (block.feedRate > 0) ? block.feedRate : currentFeed;
        if (block.gCode == "G0") {
            feed = opts_.rapidRate;
        }
        
        if (dist > 0 && feed > 0) {
            duration += dist / (feed / 60.0);  // Convert mm/min to mm/s
        }
        
        if (block.feedRate > 0) currentFeed = block.feedRate;
        lastX = x; lastY = y; lastZ = z;
    }
    
    return duration;
}

std::pair<std::array<double, 3>, std::array<double, 3>> GCodeProgram::getBounds() const {
    std::array<double, 3> minBounds = {1e9, 1e9, 1e9};
    std::array<double, 3> maxBounds = {-1e9, -1e9, -1e9};
    
    for (const auto& block : blocks_) {
        for (int i = 0; i < 3; ++i) {
            if (block.hasPosition[i]) {
                minBounds[i] = std::min(minBounds[i], block.position[i]);
                maxBounds[i] = std::max(maxBounds[i], block.position[i]);
            }
        }
    }
    
    return {minBounds, maxBounds};
}

//=============================================================================
// TestPatternGenerator Implementation
//=============================================================================

TestPatternGenerator::TestPatternGenerator(const GCodeOptions& opts)
    : opts_(opts) {}

GCodeProgram TestPatternGenerator::generateSingleAxisTest(const SingleAxisTestConfig& config) {
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    std::string testName;
    switch (config.type) {
        case SingleAxisTestType::Sinusoid: testName = "Sinusoid"; break;
        case SingleAxisTestType::Ramp: testName = "Ramp"; break;
        case SingleAxisTestType::SCurve: testName = "S-Curve"; break;
        case SingleAxisTestType::Step: testName = "Step"; break;
        case SingleAxisTestType::Triangular: testName = "Triangular"; break;
        case SingleAxisTestType::Trapezoidal: testName = "Trapezoidal"; break;
    }
    
    const char* axisNames = "XYZABCUVW";
    prog.addComment("Single axis test: " + testName + " on " + axisNames[config.axis] +
                    ", Amplitude: " + std::to_string(config.amplitude) + "mm");
    
    // Move to start position
    double startPos[3] = {0, 0, opts_.safeZ};
    startPos[config.axis % 3] = config.centerPosition - config.amplitude;
    prog.addRapid(startPos[0], startPos[1], startPos[2]);
    
    switch (config.type) {
        case SingleAxisTestType::Sinusoid:
            return generateSinusoidTest(config.axis, config.centerPosition,
                                        config.amplitude, config.frequency,
                                        config.cycles, config.velocity);
        case SingleAxisTestType::Ramp:
            return generateRampTest(config.axis, 
                                   config.centerPosition - config.amplitude,
                                   config.centerPosition + config.amplitude,
                                   config.velocity, config.cycles);
        default:
            break;
    }
    
    prog.addProgramEnd();
    return prog;
}

GCodeProgram TestPatternGenerator::generateMultiAxisTest(const MultiAxisTestConfig& config) {
    switch (config.type) {
        case MultiAxisTestType::Circle:
            return generateCircleTest(config.center[0], config.center[1], config.center[2],
                                      config.radiusU, config.feedRate, config.revolutions);
        case MultiAxisTestType::Ellipse:
            return generateEllipseTest(config.center[0], config.center[1], config.center[2],
                                       config.radiusU, config.radiusV, config.rotationAngle,
                                       config.feedRate, config.revolutions);
        case MultiAxisTestType::Helix:
            return generateHelixTest(config.center[0], config.center[1], config.center[2],
                                     config.radiusU, config.pitchW, config.feedRate,
                                     config.revolutions);
        case MultiAxisTestType::Square:
            return generateSquareTest(config.center[0], config.center[1], config.center[2],
                                      config.radiusU * 2, config.feedRate, config.revolutions);
        case MultiAxisTestType::RoundedSquare:
            return generateRoundedSquareTest(config.center[0], config.center[1], config.center[2],
                                             config.radiusU * 2, config.cornerRadius,
                                             config.feedRate, config.revolutions);
        default:
            break;
    }
    
    return GCodeProgram(opts_);
}

GCodeProgram TestPatternGenerator::generateCircleTest(
    double centerX, double centerY, double centerZ,
    double radius, double feedRate, int revolutions) {
    
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    prog.addComment("Circle test: R=" + std::to_string(radius) + 
                    " F=" + std::to_string(feedRate));
    
    // Move to start position (right side of circle)
    double startX = centerX + radius;
    double startY = centerY;
    
    prog.addRapidZ(opts_.safeZ);
    prog.addRapidXY(startX, startY);
    prog.addRapidZ(centerZ);
    
    // Full circles using G2/G3
    for (int rev = 0; rev < revolutions; ++rev) {
        // Use two semicircles for full circle
        prog.addArcCW(centerX - radius, centerY, -radius, 0, feedRate);
        prog.addArcCW(centerX + radius, centerY, radius, 0, feedRate);
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addProgramEnd();
    
    return prog;
}

GCodeProgram TestPatternGenerator::generateEllipseTest(
    double centerX, double centerY, double centerZ,
    double radiusX, double radiusY, double rotation,
    double feedRate, int revolutions) {
    
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    prog.addComment("Ellipse test: Rx=" + std::to_string(radiusX) +
                    " Ry=" + std::to_string(radiusY));
    
    double rotRad = rotation * M_PI / 180.0;
    double cosR = std::cos(rotRad);
    double sinR = std::sin(rotRad);
    
    // Start at angle 0
    double startX = centerX + radiusX * cosR;
    double startY = centerY + radiusX * sinR;
    
    prog.addRapidZ(opts_.safeZ);
    prog.addRapidXY(startX, startY);
    prog.addRapidZ(centerZ);
    
    // Approximate ellipse with line segments
    int segments = 72;
    for (int rev = 0; rev < revolutions; ++rev) {
        for (int i = 1; i <= segments; ++i) {
            double angle = 2.0 * M_PI * i / segments;
            double localX = radiusX * std::cos(angle);
            double localY = radiusY * std::sin(angle);
            
            double x = centerX + localX * cosR - localY * sinR;
            double y = centerY + localX * sinR + localY * cosR;
            
            prog.addLinearXY(x, y, feedRate);
        }
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addProgramEnd();
    
    return prog;
}

GCodeProgram TestPatternGenerator::generateHelixTest(
    double centerX, double centerY, double startZ,
    double radius, double pitch, double feedRate, int revolutions) {
    
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    prog.addComment("Helix test: R=" + std::to_string(radius) +
                    " Pitch=" + std::to_string(pitch));
    
    double startX = centerX + radius;
    
    prog.addRapidZ(opts_.safeZ);
    prog.addRapidXY(startX, centerY);
    prog.addRapidZ(startZ);
    
    // Helical arc
    double currentZ = startZ;
    int segmentsPerRev = 4;  // 4 quarter arcs per revolution
    
    for (int rev = 0; rev < revolutions; ++rev) {
        for (int seg = 0; seg < segmentsPerRev; ++seg) {
            double endAngle = (seg + 1) * M_PI / 2;
            double endX = centerX + radius * std::cos(endAngle);
            double endY = centerY + radius * std::sin(endAngle);
            double endZ = currentZ + pitch / segmentsPerRev;
            
            double startAngle = seg * M_PI / 2;
            double i = -radius * std::cos(startAngle);
            double j = -radius * std::sin(startAngle);
            
            GCodeBlock block;
            block.gCode = "G2";
            block.position[0] = endX; block.hasPosition[0] = true;
            block.position[1] = endY; block.hasPosition[1] = true;
            block.position[2] = endZ; block.hasPosition[2] = true;
            block.i = i; block.j = j; block.hasIJK = true;
            block.feedRate = feedRate;
            prog.addBlock(block);
            
            currentZ = endZ;
        }
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addProgramEnd();
    
    return prog;
}

GCodeProgram TestPatternGenerator::generateSinusoidTest(
    int axis, double center, double amplitude,
    double frequency, int cycles, double feedRate) {
    
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    const char* axisNames = "XYZABCUVW";
    prog.addComment("Sinusoid test: " + std::string(1, axisNames[axis]) +
                    " A=" + std::to_string(amplitude) +
                    " f=" + std::to_string(frequency) + "Hz");
    
    // Calculate total distance for velocity-based timing
    double period = 1.0 / frequency;
    double totalTime = cycles * period;
    double approxDistance = cycles * 4 * amplitude;  // Approximate
    double velocityMmPerSec = feedRate / 60.0;
    
    int points = static_cast<int>(approxDistance / (velocityMmPerSec * 0.001));  // ~1ms spacing
    points = std::max(100, std::min(10000, points));
    
    // Move to start
    double startPos[3] = {0, 0, opts_.safeZ};
    startPos[axis % 3] = center;
    
    prog.addRapidZ(opts_.safeZ);
    prog.addRapid(startPos[0], startPos[1], startPos[2]);
    
    // Generate sinusoid points
    double dx = 0, dy = 0, dz = 0;
    double* axisPtr = nullptr;
    switch (axis) {
        case 0: axisPtr = &dx; break;
        case 1: axisPtr = &dy; break;
        case 2: axisPtr = &dz; break;
    }
    
    double travelAxis = (axis == 0) ? 1 : 0;  // Move along perpendicular axis
    double travelLength = cycles * 50.0;  // 50mm per cycle
    
    for (int i = 0; i <= points; ++i) {
        double t = static_cast<double>(i) / points * totalTime;
        double travel = static_cast<double>(i) / points * travelLength;
        
        double sinVal = amplitude * std::sin(2.0 * M_PI * frequency * t);
        
        double x = (travelAxis == 0) ? travel : (axis == 0 ? center + sinVal : 0);
        double y = (travelAxis == 1) ? travel : (axis == 1 ? center + sinVal : 0);
        double z = (axis == 2) ? center + sinVal : opts_.safeZ;
        
        if (axis == 0) x = center + sinVal;
        else if (axis == 1) y = center + sinVal;
        else z = center + sinVal;
        
        if (travelAxis == 0) x = travel;
        else y = travel;
        
        prog.addLinear(x, y, z, feedRate);
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addProgramEnd();
    
    return prog;
}

GCodeProgram TestPatternGenerator::generateRampTest(
    int axis, double start, double end,
    double feedRate, int repeats) {
    
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    const char* axisNames = "XYZABCUVW";
    prog.addComment("Ramp test: " + std::string(1, axisNames[axis]) +
                    " " + std::to_string(start) + " to " + std::to_string(end));
    
    double pos[3] = {0, 0, opts_.safeZ};
    pos[axis % 3] = start;
    
    prog.addRapid(pos[0], pos[1], pos[2]);
    
    for (int rep = 0; rep < repeats; ++rep) {
        // Forward
        pos[axis % 3] = end;
        prog.addLinear(pos[0], pos[1], pos[2], feedRate);
        
        prog.addDwell(0.1);
        
        // Back
        pos[axis % 3] = start;
        prog.addLinear(pos[0], pos[1], pos[2], feedRate);
        
        prog.addDwell(0.1);
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addProgramEnd();
    
    return prog;
}

GCodeProgram TestPatternGenerator::generateSquareTest(
    double centerX, double centerY, double centerZ,
    double size, double feedRate, int revolutions) {
    
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    prog.addComment("Square test: Size=" + std::to_string(size));
    
    double half = size / 2;
    
    // Corners
    double corners[4][2] = {
        {centerX + half, centerY + half},
        {centerX - half, centerY + half},
        {centerX - half, centerY - half},
        {centerX + half, centerY - half}
    };
    
    prog.addRapidZ(opts_.safeZ);
    prog.addRapidXY(corners[0][0], corners[0][1]);
    prog.addRapidZ(centerZ);
    
    for (int rev = 0; rev < revolutions; ++rev) {
        for (int i = 1; i <= 4; ++i) {
            int idx = i % 4;
            prog.addLinearXY(corners[idx][0], corners[idx][1], feedRate);
        }
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addProgramEnd();
    
    return prog;
}

GCodeProgram TestPatternGenerator::generateRoundedSquareTest(
    double centerX, double centerY, double centerZ,
    double size, double cornerRadius, double feedRate, int revolutions) {
    
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    prog.addComment("Rounded square test: Size=" + std::to_string(size) +
                    " R=" + std::to_string(cornerRadius));
    
    double half = size / 2;
    double r = std::min(cornerRadius, half * 0.9);  // Limit corner radius
    
    // Start point (middle of right edge)
    prog.addRapidZ(opts_.safeZ);
    prog.addRapidXY(centerX + half, centerY);
    prog.addRapidZ(centerZ);
    
    for (int rev = 0; rev < revolutions; ++rev) {
        // Top-right corner approach
        prog.addLinearXY(centerX + half, centerY + half - r, feedRate);
        // Top-right corner arc
        prog.addArcCW(centerX + half - r, centerY + half, 0, r, feedRate);
        
        // Top edge
        prog.addLinearXY(centerX - half + r, centerY + half, feedRate);
        // Top-left corner arc
        prog.addArcCW(centerX - half, centerY + half - r, -r, 0, feedRate);
        
        // Left edge
        prog.addLinearXY(centerX - half, centerY - half + r, feedRate);
        // Bottom-left corner arc
        prog.addArcCW(centerX - half + r, centerY - half, 0, -r, feedRate);
        
        // Bottom edge
        prog.addLinearXY(centerX + half - r, centerY - half, feedRate);
        // Bottom-right corner arc
        prog.addArcCW(centerX + half, centerY - half + r, r, 0, feedRate);
        
        // Complete right edge
        prog.addLinearXY(centerX + half, centerY, feedRate);
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addProgramEnd();
    
    return prog;
}

GCodeProgram TestPatternGenerator::generateFrictionTest(
    int axis, double distance,
    const std::vector<double>& feedRates, int repeatsPerRate) {
    
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    const char* axisNames = "XYZABCUVW";
    prog.addComment("Friction test: Axis " + std::string(1, axisNames[axis]));
    
    double pos[3] = {0, 0, opts_.safeZ};
    
    for (double feedRate : feedRates) {
        prog.addComment("Feed rate: " + std::to_string(feedRate) + " mm/min");
        
        for (int rep = 0; rep < repeatsPerRate; ++rep) {
            // Forward
            pos[axis % 3] = distance;
            prog.addLinear(pos[0], pos[1], pos[2], feedRate);
            prog.addDwell(0.5);
            
            // Back
            pos[axis % 3] = 0;
            prog.addLinear(pos[0], pos[1], pos[2], feedRate);
            prog.addDwell(0.5);
        }
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addProgramEnd();
    
    return prog;
}

GCodeProgram TestPatternGenerator::generateWorkspaceSweep(
    const HeatmapConfig& heatmapConfig, double testRadius, double feedRate) {
    
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    prog.addComment("Workspace sweep for performance mapping");
    
    double xRange = heatmapConfig.maxBounds[0] - heatmapConfig.minBounds[0];
    double yRange = heatmapConfig.maxBounds[1] - heatmapConfig.minBounds[1];
    double zRange = heatmapConfig.maxBounds[2] - heatmapConfig.minBounds[2];
    
    int numX = static_cast<int>(xRange / heatmapConfig.resolution3D);
    int numY = static_cast<int>(yRange / heatmapConfig.resolution3D);
    int numZ = std::max(1, static_cast<int>(zRange / (heatmapConfig.resolution3D * 2)));
    
    for (int iz = 0; iz < numZ; ++iz) {
        double z = heatmapConfig.minBounds[2] + (iz + 0.5) * zRange / numZ;
        
        prog.addComment("Z level: " + std::to_string(z));
        
        for (int iy = 0; iy < numY; ++iy) {
            double y = heatmapConfig.minBounds[1] + (iy + 0.5) * yRange / numY;
            
            for (int ix = 0; ix < numX; ++ix) {
                double x = heatmapConfig.minBounds[0] + (ix + 0.5) * xRange / numX;
                
                // Move to position
                prog.addRapidZ(opts_.safeZ);
                prog.addRapidXY(x + testRadius, y);
                prog.addRapidZ(z);
                
                // Small circle
                prog.addArcCW(x - testRadius, y, -testRadius, 0, feedRate);
                prog.addArcCW(x + testRadius, y, testRadius, 0, feedRate);
            }
        }
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addRapidXY(0, 0);
    prog.addProgramEnd();
    
    return prog;
}

GCodeProgram TestPatternGenerator::generateCalibrationSequence(const TestSequence& sequence) {
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    prog.addComment("Calibration sequence: " + sequence.name);
    prog.addComment(sequence.description);
    prog.addBlankLine();
    
    // Generate all single axis tests
    for (const auto& config : sequence.singleAxisTests) {
        prog.addComment("=== Single axis test ===");
        auto subProg = generateSingleAxisTest(config);
        for (const auto& block : subProg.blocks()) {
            prog.addBlock(block);
        }
        prog.addDwell(1.0);
    }
    
    // Generate all multi axis tests
    for (const auto& config : sequence.multiAxisTests) {
        prog.addComment("=== Multi axis test ===");
        auto subProg = generateMultiAxisTest(config);
        for (const auto& block : subProg.blocks()) {
            prog.addBlock(block);
        }
        prog.addDwell(1.0);
    }
    
    prog.addProgramEnd();
    return prog;
}

//=============================================================================
// GCodeExporter Implementation
//=============================================================================

GCodeExporter::GCodeExporter(const GCodeOptions& opts)
    : opts_(opts) {}

GCodeProgram GCodeExporter::exportTrajectory(const std::vector<PositionSample>& samples) {
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    if (samples.empty()) {
        prog.addProgramEnd();
        return prog;
    }
    
    // Move to first point
    const auto& first = samples[0];
    prog.addRapidZ(opts_.safeZ);
    prog.addRapidXY(first.position[0], first.position[1]);
    prog.addRapidZ(first.position[2]);
    
    double lastFeed = 0;
    
    for (size_t i = 1; i < samples.size(); ++i) {
        const auto& sample = samples[i];
        
        // Calculate velocity for feed rate
        double dt = sample.timestamp - samples[i-1].timestamp;
        double dx = sample.position[0] - samples[i-1].position[0];
        double dy = sample.position[1] - samples[i-1].position[1];
        double dz = sample.position[2] - samples[i-1].position[2];
        double dist = std::sqrt(dx*dx + dy*dy + dz*dz);
        
        double feedRate = (dt > 0) ? (dist / dt * 60.0) : opts_.defaultFeedRate;
        feedRate = std::max(1.0, std::min(opts_.rapidRate, feedRate));
        
        // Only output feed rate if changed significantly
        if (std::abs(feedRate - lastFeed) / feedRate > 0.05) {
            prog.addLinear(sample.position[0], sample.position[1], sample.position[2], feedRate);
            lastFeed = feedRate;
        } else {
            prog.addLinear(sample.position[0], sample.position[1], sample.position[2]);
        }
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addProgramEnd();
    
    return prog;
}

GCodeProgram GCodeExporter::exportTrajectoryWithArcs(
    const std::vector<PositionSample>& samples, double arcTolerance) {
    
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    if (samples.empty()) {
        prog.addProgramEnd();
        return prog;
    }
    
    // Move to first point
    prog.addRapidZ(opts_.safeZ);
    prog.addRapidXY(samples[0].position[0], samples[0].position[1]);
    prog.addRapidZ(samples[0].position[2]);
    
    size_t i = 1;
    while (i < samples.size()) {
        size_t arcEnd;
        double cx, cy, r;
        bool cw;
        
        if (fitArc(samples, i, arcEnd, cx, cy, r, cw)) {
            // Output arc
            if (cw) {
                prog.addArcCW(samples[arcEnd].position[0], samples[arcEnd].position[1],
                             cx - samples[i-1].position[0], cy - samples[i-1].position[1],
                             opts_.defaultFeedRate);
            } else {
                prog.addArcCCW(samples[arcEnd].position[0], samples[arcEnd].position[1],
                              cx - samples[i-1].position[0], cy - samples[i-1].position[1],
                              opts_.defaultFeedRate);
            }
            i = arcEnd + 1;
        } else {
            // Output linear
            prog.addLinear(samples[i].position[0], samples[i].position[1],
                          samples[i].position[2], opts_.defaultFeedRate);
            i++;
        }
    }
    
    prog.addRapidZ(opts_.safeZ);
    prog.addProgramEnd();
    
    return prog;
}

bool GCodeExporter::fitArc(const std::vector<PositionSample>& samples, size_t start, size_t& end,
                           double& cx, double& cy, double& r, bool& clockwise) {
    // Simple arc fitting - check if 3+ points lie on a circle
    if (start + 2 >= samples.size()) return false;
    
    // Get three points
    double x1 = samples[start].position[0], y1 = samples[start].position[1];
    double x2 = samples[start + 1].position[0], y2 = samples[start + 1].position[1];
    double x3 = samples[start + 2].position[0], y3 = samples[start + 2].position[1];
    
    // Calculate circumcenter
    double d = 2 * (x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2));
    if (std::abs(d) < 1e-9) return false;  // Collinear
    
    double ux = ((x1*x1 + y1*y1) * (y2 - y3) + (x2*x2 + y2*y2) * (y3 - y1) + (x3*x3 + y3*y3) * (y1 - y2)) / d;
    double uy = ((x1*x1 + y1*y1) * (x3 - x2) + (x2*x2 + y2*y2) * (x1 - x3) + (x3*x3 + y3*y3) * (x2 - x1)) / d;
    
    r = std::sqrt((x1 - ux) * (x1 - ux) + (y1 - uy) * (y1 - uy));
    
    // Check if radius is reasonable
    if (r < opts_.arcMinRadius || r > 10000) return false;
    
    // Determine direction
    double cross = (x2 - x1) * (y3 - y1) - (y2 - y1) * (x3 - x1);
    clockwise = (cross < 0);
    
    cx = ux;
    cy = uy;
    
    // Find how many more points fit the arc
    end = start + 2;
    for (size_t i = start + 3; i < samples.size(); ++i) {
        double px = samples[i].position[0];
        double py = samples[i].position[1];
        double dist = std::sqrt((px - cx) * (px - cx) + (py - cy) * (py - cy));
        
        if (std::abs(dist - r) > opts_.arcTolerance) break;
        end = i;
    }
    
    return (end > start + 2);  // Need at least 3 points
}

GCodeProgram GCodeExporter::exportTestResult(const TestResult& result) {
    GCodeProgram prog(opts_);
    prog.addProgramStart();
    
    prog.addComment("Test: " + result.testName);
    prog.addComment("Type: " + result.testType);
    
    // Export desired trajectory
    prog.addComment("--- Desired Trajectory ---");
    for (const auto& sample : result.desiredSamples) {
        prog.addLinear(sample.position[0], sample.position[1], sample.position[2],
                      opts_.defaultFeedRate);
    }
    
    prog.addProgramEnd();
    return prog;
}

} // namespace MotionReplanner
