/**
 * @file GCodeProgram.cpp
 * @brief GCodeProgram class implementation
 * 
 * Split from GCodeGenerator.cpp for maintainability.
 */

#include "GCodeGenerator.hpp"
#include <fstream>
#include <algorithm>
#include <cmath>

namespace MotionReplanner {

//=============================================================================
// GCodeProgram Implementation
//=============================================================================

GCodeProgram::GCodeProgram(const GCodeOptions& opts)
    : opts_(opts), nextLineNumber_(opts.lineNumberIncrement) {}

void GCodeProgram::addBlock(const GCodeBlock& block) {
    GCodeBlock b = block;
    if (opts_.useLineNumbers && b.lineNumber < 0) {
        b.lineNumber = nextLineNumber_;
        nextLineNumber_ += opts_.lineNumberIncrement;
    }
    blocks_.push_back(b);
}

void GCodeProgram::addBlock(const std::string& line) {
    GCodeBlock block;
    block.comment = line;
    addBlock(block);
}

void GCodeProgram::addComment(const std::string& comment) {
    GCodeBlock block;
    block.comment = comment;
    blocks_.push_back(block);
}

void GCodeProgram::addBlankLine() {
    GCodeBlock block;
    blocks_.push_back(block);
}

void GCodeProgram::addProgramStart() {
    addComment("Program generated by MotionReplanner");
    
    if (opts_.useMetric) {
        addUnitsMetric();
    } else {
        addUnitsInch();
    }
    
    if (opts_.absoluteMode) {
        addAbsoluteMode();
    } else {
        addIncrementalMode();
    }
}

void GCodeProgram::addProgramEnd() {
    GCodeBlock block;
    block.mCode = "M30";
    block.comment = "End program";
    addBlock(block);
}

void GCodeProgram::addUnitsMetric() {
    GCodeBlock block;
    block.gCode = "G21";
    block.comment = "Metric units";
    addBlock(block);
}

void GCodeProgram::addUnitsInch() {
    GCodeBlock block;
    block.gCode = "G20";
    block.comment = "Inch units";
    addBlock(block);
}

void GCodeProgram::addAbsoluteMode() {
    GCodeBlock block;
    block.gCode = "G90";
    block.comment = "Absolute positioning";
    addBlock(block);
}

void GCodeProgram::addIncrementalMode() {
    GCodeBlock block;
    block.gCode = "G91";
    block.comment = "Incremental positioning";
    addBlock(block);
}

void GCodeProgram::addRapid(double x, double y, double z) {
    GCodeBlock block;
    block.gCode = "G0";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.position[2] = z; block.hasPosition[2] = true;
    addBlock(block);
    
    currentX_ = x; currentY_ = y; currentZ_ = z;
}

void GCodeProgram::addRapidXY(double x, double y) {
    GCodeBlock block;
    block.gCode = "G0";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    addBlock(block);
    
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addRapidZ(double z) {
    GCodeBlock block;
    block.gCode = "G0";
    block.position[2] = z; block.hasPosition[2] = true;
    addBlock(block);
    
    currentZ_ = z;
}

void GCodeProgram::addLinear(double x, double y, double z, double feedRate) {
    GCodeBlock block;
    block.gCode = "G1";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.position[2] = z; block.hasPosition[2] = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y; currentZ_ = z;
}

void GCodeProgram::addLinearXY(double x, double y, double feedRate) {
    GCodeBlock block;
    block.gCode = "G1";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addArcCW(double x, double y, double i, double j, double feedRate) {
    GCodeBlock block;
    block.gCode = "G2";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.i = i; block.j = j; block.hasIJK = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addArcCCW(double x, double y, double i, double j, double feedRate) {
    GCodeBlock block;
    block.gCode = "G3";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.i = i; block.j = j; block.hasIJK = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addArcCW_R(double x, double y, double r, double feedRate) {
    GCodeBlock block;
    block.gCode = "G2";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.r = r; block.hasR = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addArcCCW_R(double x, double y, double r, double feedRate) {
    GCodeBlock block;
    block.gCode = "G3";
    block.position[0] = x; block.hasPosition[0] = true;
    block.position[1] = y; block.hasPosition[1] = true;
    block.r = r; block.hasR = true;
    
    if (feedRate > 0 && feedRate != currentFeed_) {
        block.feedRate = feedRate;
        currentFeed_ = feedRate;
    }
    
    addBlock(block);
    currentX_ = x; currentY_ = y;
}

void GCodeProgram::addDwell(double seconds) {
    GCodeBlock block;
    block.gCode = "G4";
    std::ostringstream ss;
    ss << "G4 P" << std::fixed << std::setprecision(3) << seconds;
    block.comment = "";
    addBlock(ss.str());
}

void GCodeProgram::addToolChange(int toolNumber) {
    GCodeBlock block;
    std::ostringstream ss;
    ss << "T" << toolNumber << " M6";
    addBlock(ss.str());
}

void GCodeProgram::addSpindleOn(double rpm, bool cw) {
    GCodeBlock block;
    block.mCode = cw ? "M3" : "M4";
    block.spindleSpeed = rpm;
    addBlock(block);
}

void GCodeProgram::addSpindleOff() {
    GCodeBlock block;
    block.mCode = "M5";
    addBlock(block);
}

void GCodeProgram::addCoolantOn() {
    GCodeBlock block;
    block.mCode = "M8";
    addBlock(block);
}

void GCodeProgram::addCoolantOff() {
    GCodeBlock block;
    block.mCode = "M9";
    addBlock(block);
}

void GCodeProgram::addFeedRate(double feedRate) {
    GCodeBlock block;
    block.feedRate = feedRate;
    addBlock(block);
    currentFeed_ = feedRate;
}

std::string GCodeProgram::toString() const {
    std::ostringstream ss;
    write(ss);
    return ss.str();
}

bool GCodeProgram::saveToFile(const std::string& filename) const {
    std::ofstream file(filename);
    if (!file.is_open()) return false;
    write(file);
    return file.good();
}

void GCodeProgram::write(std::ostream& out) const {
    for (const auto& block : blocks_) {
        std::string line = block.toString(opts_);
        if (!line.empty() || block.comment.empty()) {
            out << line << "\n";
        }
    }
}

double GCodeProgram::estimateDuration() const {
    double duration = 0.0;
    double lastX = 0, lastY = 0, lastZ = 0;
    double currentFeed = opts_.defaultFeedRate;
    
    for (const auto& block : blocks_) {
        double x = lastX, y = lastY, z = lastZ;
        
        if (block.hasPosition[0]) x = block.position[0];
        if (block.hasPosition[1]) y = block.position[1];
        if (block.hasPosition[2]) z = block.position[2];
        
        double dist = std::sqrt(
            (x - lastX) * (x - lastX) +
            (y - lastY) * (y - lastY) +
            (z - lastZ) * (z - lastZ)
        );
        
        double feed = (block.feedRate > 0) ? block.feedRate : currentFeed;
        if (block.gCode == "G0") {
            feed = opts_.rapidRate;
        }
        
        if (dist > 0 && feed > 0) {
            duration += dist / (feed / 60.0);  // Convert mm/min to mm/s
        }
        
        if (block.feedRate > 0) currentFeed = block.feedRate;
        lastX = x; lastY = y; lastZ = z;
    }
    
    return duration;
}

std::pair<std::array<double, 3>, std::array<double, 3>> GCodeProgram::getBounds() const {
    std::array<double, 3> minBounds = {1e9, 1e9, 1e9};
    std::array<double, 3> maxBounds = {-1e9, -1e9, -1e9};
    
    for (const auto& block : blocks_) {
        for (int i = 0; i < 3; ++i) {
            if (block.hasPosition[i]) {
                minBounds[i] = std::min(minBounds[i], block.position[i]);
                maxBounds[i] = std::max(maxBounds[i], block.position[i]);
            }
        }
    }
    
    return {minBounds, maxBounds};
}

} // namespace MotionReplanner
