/**
 * @file klipper_http.cpp
 * @brief Example: Simulated 3D printer with HTTP/WebSocket server for Mainsail/Fluidd.
 *
 * @details
 * This example runs a fully simulated 3D printer that can be controlled from
 * Mainsail or Fluidd via the Moonraker HTTP/WebSocket API. It combines:
 *
 *   - KlippyInstance: full G-code execution, printer object model, print control
 *   - SingleZoneOven thermal models (from tether_simulation) for extruder and
 *     bed heaters, with PID control and realistic warm-up / cool-down dynamics
 *   - G-code print playback from the virtual SD card with live toolhead
 *     position updates and progress tracking
 *   - KlippyHttpServer: native HTTP/WebSocket transport for Mainsail/Fluidd
 *
 * The printer simulates:
 *   - PID-controlled heaters with realistic thermal dynamics (warm-up/cool-down)
 *   - G-code print playback with live toolhead position updates
 *   - Print progress, duration, and filament usage tracking
 *   - Fan, probe, and endstop peripherals
 *
 * Usage:
 *   klipper_http [-p PORT] [-M] [-u PATH] [-m DIR] [-f DIR] [-w DIR]
 *                [-g DIR] [-c DIR] [-l DIR] [-k KEY] [-A] [-t MS]
 *
 * Web UI options:
 *   --mainsail DIR   Clone and build Mainsail into DIR (asks y/N first).
 *                     If DIR already contains a built dist/, reuses it.
 *   --fluidd DIR     Same for Fluidd.
 *   --web-root DIR   Serve pre-built static assets from DIR as-is.
 *
 * Once running, open http://localhost:PORT/ in a browser. You can:
 *   - Set heater targets and watch temperatures rise/fall
 *   - Start prints from the G-code browser (a sample file is generated)
 *   - Send G-code commands from the console
 *   - Monitor toolhead position, print progress, and fan speed
 *
 * Docker deployment (alternative):
 *   See docs/MainsailDocker.md for running Mainsail in a Docker container.
 */

#include "tether/klipper/klippy/KlippyInstance.hpp"
#include "tether/klipper/klippy/KlippyUdsHelpText.hpp"
#include "tether/klipper/http/KlippyHttpServer.hpp"
#include "tether/simulation/systems/thermal/SingleZoneOven.hpp"

#include <argparse/argparse.hpp>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <memory>
#include <mutex>
#include <stop_token>
#include <string>
#include <thread>

using namespace tether::klipper::klippy;
using namespace tether::klipper::http;
using namespace tether::klipper::objects;

// ============================================================================
// Thermal simulation
// ============================================================================

/// @brief Thermal plant for one heater, backed by a SingleZoneOven model.
///
/// The oven dynamics are:
///   C_th * dT/dt = eta * Q - (T - T_amb) / R_th
/// where Q is the heater power in Watts.  The PID controller in the Heater
/// class produces a PWM duty cycle in [0, 1]; we scale it by maxPowerW to
/// obtain Q.
struct ThermalPlant {
    Simulation::SingleZoneOven oven;
    double maxPowerW;
    double pwm = 0.0;   ///< Last applied PWM duty cycle (0..1)
    double temp = 25.0; ///< Current plant temperature [°C]
    double dt;          ///< Simulation time step [s]

    ThermalPlant(double C_th, double R_th, double eta, double T_amb,
                 double maxPower, double step)
        : maxPowerW(maxPower), temp(T_amb), dt(step) {
        oven.setParameter("C_th", C_th);
        oven.setParameter("R_th", R_th);
        oven.setParameter("eta", eta);
        oven.setParameter("T_amb", T_amb);
    }

    /// Advance the plant by one dt using forward Euler.
    void step() {
        double Q = pwm * maxPowerW;
        auto d = oven.dynamics(0.0, {temp}, {Q});
        temp += d[0] * dt;
    }
};

// ============================================================================
// Default printer.cfg for the simulated printer
// ============================================================================

/// @brief Write a default printer.cfg matching the simulated printer.
/// @param path Full path to the output file.
static void generateDefaultPrinterCfg(const std::string& path) {
    std::ofstream f(path);
    if (!f.is_open()) return;

    f << "# Tether simulated printer configuration\n";
    f << "# Auto-generated by klipper_http example\n\n";

    f << "[printer]\n";
    f << "kinematics: cartesian\n";
    f << "max_velocity: 3000\n";
    f << "max_accel: 3000\n";
    f << "max_accel_to_decel: 1500\n";
    f << "square_corner_velocity: 5.0\n\n";

    f << "[mcu]\n";
    f << "serial: /tmp/klippy_uds\n\n";

    f << "[extruder]\n";
    f << "step_pin: PA0\n";
    f << "dir_pin: PA1\n";
    f << "enable_pin: !PA2\n";
    f << "microsteps: 16\n";
    f << "rotation_distance: 33.500\n";
    f << "nozzle_diameter: 0.400\n";
    f << "filament_diameter: 1.750\n";
    f << "heater_pin: PB0\n";
    f << "sensor_type: EPCOS 100K B57560G104F\n";
    f << "sensor_pin: PC0\n";
    f << "control: pid\n";
    f << "pid_Kp: 14.0\n";
    f << "pid_Ki: 0.1\n";
    f << "pid_Kd: 50.0\n";
    f << "min_temp: 0\n";
    f << "max_temp: 300\n";
    f << "min_extrude_temp: 170\n";
    f << "max_extrude_only_distance: 100\n\n";

    f << "[heater_bed]\n";
    f << "heater_pin: PB1\n";
    f << "sensor_type: EPCOS 100K B57560G104F\n";
    f << "sensor_pin: PC1\n";
    f << "control: pid\n";
    f << "pid_Kp: 10.0\n";
    f << "pid_Ki: 0.05\n";
    f << "pid_Kd: 30.0\n";
    f << "min_temp: 0\n";
    f << "max_temp: 120\n\n";

    f << "[fan]\n";
    f << "pin: PB2\n";
    f << "max_power: 1.0\n";
    f << "kick_start_time: 0.1\n\n";

    f << "[controller_fan controller_fan]\n";
    f << "pin: PB3\n";
    f << "max_power: 1.0\n";
    f << "kick_start_time: 0.1\n\n";

    f << "[heater_fan heater_fan]\n";
    f << "pin: PB4\n";
    f << "heater: extruder\n";
    f << "heater_temp: 50.0\n\n";

    f << "[stepper_x]\n";
    f << "step_pin: PC2\n";
    f << "dir_pin: PC3\n";
    f << "enable_pin: !PC4\n";
    f << "microsteps: 16\n";
    f << "rotation_distance: 40\n";
    f << "endstop_pin: ^PC5\n";
    f << "position_endstop: 0\n";
    f << "position_max: 300\n";
    f << "homing_speed: 50\n";
    f << "second_homing_speed: 10\n\n";

    f << "[stepper_y]\n";
    f << "step_pin: PC6\n";
    f << "dir_pin: PC7\n";
    f << "enable_pin: !PC8\n";
    f << "microsteps: 16\n";
    f << "rotation_distance: 40\n";
    f << "endstop_pin: ^PC9\n";
    f << "position_endstop: 0\n";
    f << "position_max: 300\n";
    f << "homing_speed: 50\n";
    f << "second_homing_speed: 10\n\n";

    f << "[stepper_z]\n";
    f << "step_pin: PD0\n";
    f << "dir_pin: PD1\n";
    f << "enable_pin: !PD2\n";
    f << "microsteps: 16\n";
    f << "rotation_distance: 8\n";
    f << "endstop_pin: ^PD3\n";
    f << "position_endstop: 0\n";
    f << "position_max: 400\n";
    f << "homing_speed: 10\n";
    f << "second_homing_speed: 2\n\n";

    f << "[virtual_sdcard]\n";
    f << "path: " << std::getenv("HOME") << "/.local/share/tether/gcodes\n\n";

    f << "[display_status]\n\n";

    f << "[pause_resume]\n\n";

    f << "[gcode_macro PAUSE]\n";
    f << "rename_existing: BASE_PAUSE\n";
    f << "gcode: PAUSE\n\n";

    f << "[gcode_macro RESUME]\n";
    f << "rename_existing: BASE_RESUME\n";
    f << "gcode: RESUME\n\n";

    f << "[gcode_macro CANCEL_PRINT]\n";
    f << "rename_existing: BASE_CANCEL_PRINT\n";
    f << "gcode: CANCEL_PRINT\n\n";

    f << "[gcode_macro START_PRINT]\n";
    f << "gcode: M117 Starting print...\n\n";

    f << "[gcode_macro END_PRINT]\n";
    f << "gcode: M117 Print complete\n";
}

// ============================================================================
// G-code sample file generation
// ============================================================================

/// @brief Generate a sample G-code file that prints a small calibration square.
/// @param path Full path to the output file.
/// @param layers Number of print layers to generate.
static void generateSampleGcode(const std::string& path, int layers) {
    std::ofstream f(path);
    if (!f.is_open()) return;

    f << "; Tether simulated print - calibration square\n";
    f << "; Generated by klipper_http example\n\n";
    f << "G28 ; home all axes\n";
    f << "M140 S60 ; set bed temperature\n";
    f << "M104 S210 ; set hotend temperature\n";
    f << "G1 Z5 F3000 ; lift Z before moving\n";
    f << "G1 X10 Y10 F3000 ; move to start position\n\n";

    const double layerHeight = 0.2;
    const double squareSize = 80.0;
    const double extrudePerSide = 35.0;

    for (int layer = 0; layer < layers; ++layer) {
        double z = layerHeight * (layer + 1);
        f << "; --- Layer " << (layer + 1) << " (Z=" << z << ") ---\n";
        f << std::format("G1 Z{:.2f} F300\n", z);
        f << std::format("G1 X{:.1f} Y10.0 E{:.1f} F600\n",
                         10.0 + squareSize, extrudePerSide);
        f << std::format("G1 X{:.1f} Y{:.1f} E{:.1f}\n",
                         10.0 + squareSize, 10.0 + squareSize, extrudePerSide);
        f << std::format("G1 X10.0 Y{:.1f} E{:.1f}\n",
                         10.0 + squareSize, extrudePerSide);
        f << std::format("G1 X10.0 Y10.0 E{:.1f}\n", extrudePerSide);
        f << std::format("; M73 P{}\n",
                         static_cast<int>(100.0 * (layer + 1) / layers));
    }

    f << "\n; --- Print complete ---\n";
    f << "G1 Z10 F3000 ; lift Z\n";
    f << "G1 X0 Y0 F3000 ; return home\n";
    f << "M104 S0 ; turn off hotend\n";
    f << "M140 S0 ; turn off bed\n";
    f << "M107 ; turn off fan\n";
}

// ============================================================================
// Main
// ============================================================================

/// @brief Resolve a writable default data directory.
/// Uses $XDG_DATA_HOME/tether, $HOME/.local/share/tether, or /tmp/tether
/// (in that order) so the example never tries to write to /etc or /var.
static std::string defaultDataDir(const std::string& subdir) {
    namespace fs = std::filesystem;
    // 1. XDG_DATA_HOME
    if (const char* xdg = std::getenv("XDG_DATA_HOME"); xdg && *xdg) {
        return (fs::path(xdg) / "tether" / subdir).string();
    }
    // 2. $HOME/.local/share/tether
    if (const char* home = std::getenv("HOME"); home && *home) {
        return (fs::path(home) / ".local" / "share" / "tether" / subdir).string();
    }
    // 3. /tmp/tether (always writable)
    return (fs::path("/tmp/tether") / subdir).string();
}

/// @brief Resolve a writable default config directory.
static std::string defaultConfigDir() {
    namespace fs = std::filesystem;
    if (const char* xdg = std::getenv("XDG_CONFIG_HOME"); xdg && *xdg) {
        return (fs::path(xdg) / "tether").string();
    }
    if (const char* home = std::getenv("HOME"); home && *home) {
        return (fs::path(home) / ".config" / "tether").string();
    }
    return "/tmp/tether/config";
}

// ============================================================================
// Web UI (Mainsail / Fluidd) setup
// ============================================================================

/// @brief Ask the user a yes/no question on stdin.
/// @return true if the user answered 'y' or 'Y', false otherwise.
static bool askYesNo(const std::string& question) {
    std::printf("%s [y/N] ", question.c_str());
    std::fflush(stdout);
    std::string line;
    if (!std::getline(std::cin, line)) return false;  // EOF / no stdin
    return !line.empty() && (line[0] == 'y' || line[0] == 'Y');
}

/// @brief Run a shell command, streaming its output to stdout/stderr.
/// @return true if the command exited with status 0.
static bool runCommand(const std::string& cmd) {
    std::printf("  $ %s\n", cmd.c_str());
    std::fflush(stdout);
    int rc = std::system(cmd.c_str());
    if (rc != 0) {
        std::fprintf(stderr, "  (exit status %d)\n", rc);
    }
    return rc == 0;
}

/// @brief Check if a directory looks like a built Mainsail/Fluidd dist.
static bool isBuiltDist(const std::filesystem::path& dir) {
    namespace fs = std::filesystem;
    return fs::exists(dir / "index.html") &&
           fs::exists(dir / "config.json");
}

/// @brief Check if a file contains a given substring (used to detect whether
///        an existing config.json is already in the Fluidd schema).
static bool fileContains(const std::filesystem::path& path, const std::string& needle) {
    std::ifstream f(path);
    if (!f.is_open()) return false;
    std::string content((std::istreambuf_iterator<char>(f)),
                         std::istreambuf_iterator<char>());
    return content.find(needle) != std::string::npos;
}

/// @brief Write a Mainsail/Fluidd config.json that points to the given port.
///
/// Mainsail and Fluidd use **different config.json schemas**:
/// - Mainsail: `{ "instances": [{ "hostname": "localhost", "port": PORT }] }`
/// - Fluidd:   `{ "endpoints": [], "blacklist": [...], "hosted": false, "themePresets": [...] }`
///
/// When Tether serves both the SPA and the API on the same port, Fluidd's
/// default `endpoints: []` makes it fall back to the browser URL, which is
/// already correct.  So for Fluidd we only write a config if one is missing
/// or is in the wrong (Mainsail) schema — we never overwrite a valid Fluidd
/// config because it contains themePresets we don't want to clobber.
static void writeWebUiConfig(const std::filesystem::path& distDir,
                              const std::string& uiName, uint16_t port) {
    namespace fs = std::filesystem;
    std::error_code ec;
    fs::create_directories(distDir, ec);
    auto configPath = distDir / "config.json";

    // Fluidd: preserve existing valid config; only write if missing or wrong schema.
    if (uiName == "Fluidd") {
        if (fs::exists(configPath) && fileContains(configPath, "\"endpoints\"")) {
            // Existing Fluidd config.json is valid — don't clobber themePresets etc.
            return;
        }
        // Write a minimal Fluidd config.json.  endpoints: [] makes Fluidd fall
        // back to the browser URL (which is where Tether is serving).
        std::ofstream f(configPath);
        if (!f.is_open()) return;
        f << "{\n"
          << "  \"blacklist\": [\"fluidd.xyz\", \"fluidd.net\"],\n"
          << "  \"endpoints\": [],\n"
          << "  \"hosted\": false,\n"
          << "  \"themePresets\": []\n"
          << "}\n";
        return;
    }

    // Mainsail format:
    //   { "instances": [{ "hostname": "localhost", "port": <port> }] }
    std::ofstream f(configPath);
    if (!f.is_open()) return;
    f << "{\n"
      << "  \"instances\": [\n"
      << "    {\n"
      << "      \"hostname\": \"localhost\",\n"
      << "      \"port\": " << port << "\n"
      << "    }\n"
      << "  ]\n"
      << "}\n";
}

/// @brief Check whether a shell command is available on PATH.
static bool commandAvailable(const std::string& cmd) {
    // `command -v` is POSIX; returns 0 if cmd resolves on PATH.
    return std::system(("command -v " + cmd + " >/dev/null 2>&1").c_str()) == 0;
}

/// @brief Detected package manager for a Node project.
struct PackageManager {
    std::string name;       ///< "pnpm", "yarn", or "npm" (for user-facing messages).
    std::string installCmd; ///< Shell token after "cd <dir> && " (e.g. "corepack pnpm install").
    std::string buildCmd;   ///< Shell token after "cd <dir> && " (e.g. "corepack pnpm run build").
};

/// @brief Detect the package manager for a Node project from its lockfile.
///
/// pnpm-lock.yaml  → pnpm  (Fluidd uses the `catalog:` protocol in package.json
///                          overrides, which npm cannot resolve — EUNSUPPORTEDPROTOCOL.
///                          Node ≥16.9 ships corepack, so prefer `corepack pnpm`
///                          to avoid needing a global pnpm install.)
/// yarn.lock       → yarn  (prefer corepack yarn, fall back to bare yarn)
/// otherwise       → npm
///
/// If a pnpm-lock.yaml is present but neither corepack nor pnpm is available,
/// we warn and fall back to npm (which will likely fail on catalog: URLs, but
/// the error is then self-explanatory).
static PackageManager detectPackageManager(const std::filesystem::path& dir) {
    namespace fs = std::filesystem;
    if (fs::exists(dir / "pnpm-lock.yaml")) {
        if (commandAvailable("corepack")) {
            return {"pnpm", "corepack pnpm install", "corepack pnpm run build"};
        }
        if (commandAvailable("pnpm")) {
            return {"pnpm", "pnpm install", "pnpm run build"};
        }
        std::fprintf(stderr,
            "Warning: pnpm-lock.yaml found but neither corepack nor pnpm is on PATH; "
            "falling back to npm (will fail with EUNSUPPORTEDPROTOCOL if package.json "
            "uses the catalog: protocol — install pnpm or Node >=16.9 for corepack).\n");
    } else if (fs::exists(dir / "yarn.lock")) {
        if (commandAvailable("corepack")) {
            return {"yarn", "corepack yarn install", "corepack yarn run build"};
        }
        if (commandAvailable("yarn")) {
            return {"yarn", "yarn install", "yarn run build"};
        }
    }
    return {"npm", "npm install", "npm run build"};
}

/// @brief Run `install` then `build` for a Node project using the detected PM.
/// @return true if both commands exited 0.
static bool installAndBuild(const std::filesystem::path& dir, const PackageManager& pm) {
    std::string cd = "cd " + dir.string();
    if (!runCommand(cd + " && " + pm.installCmd)) {
        std::fprintf(stderr, "%s install failed.\n", pm.name.c_str());
        return false;
    }
    if (!runCommand(cd + " && " + pm.buildCmd)) {
        std::fprintf(stderr, "%s build failed.\n", pm.name.c_str());
        return false;
    }
    return true;
}

/// @brief Ensure a web UI (Mainsail or Fluidd) is built and return the dist path.
///
/// @param uiDir     Directory passed via --mainsail or --fluidd.
/// @param repoUrl   Git URL to clone from if the directory doesn't exist.
/// @param uiName    Human-readable name ("Mainsail" or "Fluidd").
/// @param subdirName  Name for the subdirectory if uiDir already exists
///                    (e.g. "mainsail" or "fluidd").
/// @param port      Port for the config.json.
/// @return Path to the dist/ directory containing index.html, or empty on failure.
static std::string ensureWebUi(const std::string& uiDir,
                                const std::string& repoUrl,
                                const std::string& uiName,
                                const std::string& subdirName,
                                uint16_t port) {
    namespace fs = std::filesystem;
    fs::path dir(uiDir);
    fs::path distDir = dir / "dist";

    // Case 1: dist/ already has index.html — already built, just use it.
    if (isBuiltDist(distDir)) {
        std::printf("%s already built at %s\n", uiName.c_str(),
                    distDir.string().c_str());
        writeWebUiConfig(distDir, uiName, port);
        return distDir.string();
    }

    // Case 2: directory exists and looks like the source (has package.json)
    //         but not built yet — ask to build.
    if (fs::exists(dir / "package.json")) {
        auto pm = detectPackageManager(dir);
        std::printf("%s source found at %s but not built.\n\n",
                    uiName.c_str(), dir.string().c_str());
        std::printf("I will run the following commands to build it:\n");
        std::printf("  cd %s\n", dir.string().c_str());
        std::printf("  %s\n", pm.installCmd.c_str());
        std::printf("  %s\n\n", pm.buildCmd.c_str());
        if (!askYesNo("Proceed?")) {
            std::printf("Skipped. Continuing without %s.\n", uiName.c_str());
            return "";
        }
        std::printf("\n");
        if (!installAndBuild(dir, pm)) return "";
        if (!isBuiltDist(distDir)) {
            std::fprintf(stderr, "Build completed but dist/index.html not found.\n");
            return "";
        }
        writeWebUiConfig(distDir, uiName, port);
        return distDir.string();
    }

    // Case 3: directory already exists but is NOT the source.
    //         Check if a subdirectory with the UI name already exists
    //         and is either built or a source checkout.  If so, use it.
    //         Otherwise, ask to create the subdirectory and clone there.
    if (fs::exists(dir)) {
        fs::path subDir = dir / subdirName;
        fs::path subDist = subDir / "dist";

        // Subdirectory already has a built dist — reuse it.
        if (isBuiltDist(subDist)) {
            std::printf("%s already built at %s\n", uiName.c_str(),
                        subDist.string().c_str());
            writeWebUiConfig(subDist, uiName, port);
            return subDist.string();
        }

        // Subdirectory exists and looks like the source — build it.
        if (fs::exists(subDir / "package.json")) {
            dir = subDir;
            distDir = subDist;
            auto pm = detectPackageManager(dir);
            std::printf("%s source found at %s but not built.\n\n",
                        uiName.c_str(), dir.string().c_str());
            std::printf("I will run the following commands to build it:\n");
            std::printf("  cd %s\n", dir.string().c_str());
            std::printf("  %s\n", pm.installCmd.c_str());
            std::printf("  %s\n\n", pm.buildCmd.c_str());
            if (!askYesNo("Proceed?")) {
                std::printf("Skipped. Continuing without %s.\n", uiName.c_str());
                return "";
            }
            std::printf("\n");
            if (!installAndBuild(dir, pm)) return "";
            if (!isBuiltDist(distDir)) {
                std::fprintf(stderr, "Build completed but dist/index.html not found.\n");
                return "";
            }
            writeWebUiConfig(distDir, uiName, port);
            return distDir.string();
        }

        // Subdirectory doesn't exist — ask to create it and clone.
        std::printf("Directory %s already exists but does not contain %s.\n\n",
                    dir.string().c_str(), uiName.c_str());
        std::printf("Create a '%s' subdirectory and clone there?\n",
                    subdirName.c_str());
        std::printf("  -> %s\n\n", subDir.string().c_str());
        if (!askYesNo("Proceed?")) {
            std::printf("Skipped. Continuing without %s.\n", uiName.c_str());
            return "";
        }
        dir = subDir;
        distDir = subDist;
        std::printf("\n");
        // Fall through to clone + build below.
    } else {
        std::printf("%s not found at %s.\n\n", uiName.c_str(),
                    dir.string().c_str());
    }

    // Clone + build into dir.
    // The package manager can only be detected after the clone (lockfile is
    // part of the repo), so the announcement lists a placeholder; the actual
    // install/build commands are resolved once the source is on disk.
    std::printf("I will run the following commands:\n");
    std::printf("  git clone %s %s\n", repoUrl.c_str(), dir.string().c_str());
    std::printf("  cd %s\n", dir.string().c_str());
    std::printf("  <detected package manager> install\n");
    std::printf("  <detected package manager> run build\n\n");
    if (!askYesNo("Proceed?")) {
        std::printf("Skipped. Continuing without %s.\n", uiName.c_str());
        return "";
    }
    std::printf("\n");
    if (!runCommand("git clone " + repoUrl + " " + dir.string())) {
        std::fprintf(stderr, "git clone failed.\n");
        return "";
    }
    auto pm = detectPackageManager(dir);
    std::printf("Detected package manager: %s\n", pm.name.c_str());
    if (!installAndBuild(dir, pm)) return "";
    if (!isBuiltDist(distDir)) {
        std::fprintf(stderr, "Build completed but dist/index.html not found.\n");
        return "";
    }
    writeWebUiConfig(distDir, uiName, port);
    std::printf("\n%s built successfully at %s\n",
                uiName.c_str(), distDir.string().c_str());
    return distDir.string();
}

int main(int argc, char* argv[]) {
    // ------------------------------------------------------------------
    // Argument parsing (argparse)
    // ------------------------------------------------------------------
    argparse::ArgumentParser program("klipper_http", "1.0",
        argparse::default_arguments::help);

    program.add_argument("-p", "--port")
        .scan<'i', int>()
        .default_value(7125)
        .help("HTTP listen port (default: 7125)");

    program.add_argument("-M", "--with-moonraker")
        .implicit_value(true)
        .default_value(false)
        .help("Enable UDS transport for a separate Moonraker process "
              "(disabled by default; the built-in HTTP server replaces Moonraker)");

    program.add_argument("-u", "--uds-path")
        .default_value(std::string("/tmp/klippy_uds"))
        .help("UDS socket path (only used with --with-moonraker)");

    program.add_argument("-w", "--web-root")
        .default_value(std::string(""))
        .help("Directory with pre-built Mainsail/Fluidd static assets (served as-is)");

    program.add_argument("-m", "--mainsail")
        .default_value(std::string(""))
        .help("Path to Mainsail source directory. If not built yet, will clone "
              "and build automatically (asks for confirmation first).");

    program.add_argument("-f", "--fluidd")
        .default_value(std::string(""))
        .help("Path to Fluidd source directory. If not built yet, will clone "
              "and build automatically (asks for confirmation first).");

    program.add_argument("-g", "--gcodes-root")
        .default_value(defaultDataDir("gcodes"))
        .help("G-code file root");

    program.add_argument("-c", "--config-root")
        .default_value(defaultConfigDir())
        .help("Config file root");

    program.add_argument("-l", "--logs-root")
        .default_value(defaultDataDir("logs"))
        .help("Log file root");

    program.add_argument("-k", "--api-key")
        .default_value(std::string("tether_default_api_key"))
        .help("API key for authentication");

    program.add_argument("-A", "--no-auth")
        .implicit_value(true)
        .default_value(false)
        .help("Disable authentication");

    program.add_argument("-t", "--sim-tick-ms")
        .scan<'i', int>()
        .default_value(100)
        .help("Simulation tick interval in ms (default: 100, min: 10)");

    try {
        program.parse_args(argc, argv);
    } catch (const std::exception& e) {
        std::cerr << e.what() << "\n" << program;
        return 1;
    }

    const auto port = static_cast<uint16_t>(program.get<int>("--port"));
    const bool withMoonraker = program.get<bool>("--with-moonraker");
    const auto udsPath = program.get<std::string>("--uds-path");
    auto webRoot = program.get<std::string>("--web-root");
    const auto mainsailDir = program.get<std::string>("--mainsail");
    const auto fluiddDir = program.get<std::string>("--fluidd");
    const auto gcodesRoot = program.get<std::string>("--gcodes-root");
    const auto configRoot = program.get<std::string>("--config-root");
    const auto logsRoot = program.get<std::string>("--logs-root");
    const auto apiKey = program.get<std::string>("--api-key");
    const bool requireAuth = !program.get<bool>("--no-auth");
    int simTickMs = program.get<int>("--sim-tick-ms");
    if (simTickMs < 10) simTickMs = 10;

    // ------------------------------------------------------------------
    // Resolve web UI directory (--mainsail or --fluidd take priority
    // over --web-root).  If the source isn't built yet, ask permission
    // and clone + build automatically.
    // ------------------------------------------------------------------
    if (!mainsailDir.empty()) {
        std::string dist = ensureWebUi(
            mainsailDir,
            "https://github.com/mainsail-crew/mainsail.git",
            "Mainsail", "mainsail", port);
        if (!dist.empty()) webRoot = dist;
    } else if (!fluiddDir.empty()) {
        std::string dist = ensureWebUi(
            fluiddDir,
            "https://github.com/fluidd-core/fluidd.git",
            "Fluidd", "fluidd", port);
        if (!dist.empty()) webRoot = dist;
    }

    // Signal handling: block SIGINT/SIGTERM in this thread BEFORE starting
    // any other threads.  All threads created after this inherit the blocked
    // mask, so Drogon's signal handler (if it installs one) will never fire.
    // The main thread uses sigwait() to synchronously wait for the signal.
    sigset_t mask;
    sigemptyset(&mask);
    sigaddset(&mask, SIGINT);
    sigaddset(&mask, SIGTERM);
    pthread_sigmask(SIG_BLOCK, &mask, nullptr);

    // Ensure directories exist (use error_code overload so we don't throw)
    auto ensureDir = [](const std::string& path, const char* label) {
        std::error_code ec;
        std::filesystem::create_directories(path, ec);
        if (ec) {
            std::fprintf(stderr,
                         "Warning: cannot create %s directory '%s': %s\n",
                         label, path.c_str(), ec.message().c_str());
            std::fprintf(stderr,
                         "Use --%s DIR to specify a writable path.\n", label);
            return false;
        }
        return true;
    };
    if (!ensureDir(gcodesRoot, "gcodes-root") ||
        !ensureDir(configRoot, "config-root") ||
        !ensureDir(logsRoot, "logs-root")) {
        return 1;
    }

    // Generate a sample G-code file so the user can test printing immediately
    const std::string sampleFile = "tether_calibration_square.gcode";
    const std::string samplePath =
        (std::filesystem::path(gcodesRoot) / sampleFile).string();
    generateSampleGcode(samplePath, 100);

    // Create empty Mainsail theme files so it doesn't get 404s on startup.
    // Mainsail probes /server/files/config/.theme/default.json and
    // maintenance.json as optional theme overrides.
    {
        namespace fs = std::filesystem;
        fs::path themeDir = fs::path(configRoot) / ".theme";
        std::error_code ec;
        fs::create_directories(themeDir, ec);
        for (const char* name : {"default.json", "maintenance.json"}) {
            fs::path p = themeDir / name;
            if (!fs::exists(p)) {
                std::ofstream f(p);
                if (f.is_open()) f << "{}\n";
            }
        }
    }

    const double simDt = simTickMs / 1000.0;

    std::printf("=== Tether Simulated 3D Printer (Moonraker Replacement) ===\n\n");
    std::printf("Configuration:\n");
    std::printf("  HTTP port:       %u\n", port);
    std::printf("  UDS (Moonraker): %s", withMoonraker ? "enabled" : "disabled");
    if (withMoonraker) std::printf("  (%s)", udsPath.c_str());
    std::printf("\n");
    std::printf("  Web root:        %s\n",
                webRoot.empty() ? "(disabled)" : webRoot.c_str());
    std::printf("  G-code root:     %s\n", gcodesRoot.c_str());
    std::printf("  Config root:     %s\n", configRoot.c_str());
    std::printf("  Logs root:       %s\n", logsRoot.c_str());
    std::printf("  Auth required:   %s\n", requireAuth ? "yes" : "no");
    std::printf("  API key:         %s\n", apiKey.c_str());
    std::printf("  Sim tick:        %d ms\n", simTickMs);
    std::printf("  Sample G-code:   %s\n\n", sampleFile.c_str());
    std::fflush(stdout);

    // ------------------------------------------------------------------
    // Step 1: Create the KlippyInstance (full G-code + object model + UDS)
    // ------------------------------------------------------------------
    // Generate a default printer.cfg if it doesn't exist, then load it
    // so configfile.settings is populated for Mainsail.
    const std::string printerCfgPath = configRoot + "/printer.cfg";
    if (!std::filesystem::exists(printerCfgPath)) {
        generateDefaultPrinterCfg(printerCfgPath);
        std::printf("Generated default printer.cfg at %s\n", printerCfgPath.c_str());
    }

    KlippyInstanceConfig instCfg;
    instCfg.udsConfig.socketPath = udsPath;
    instCfg.udsConfig.configFile = printerCfgPath;
    instCfg.sdcardDir = gcodesRoot;
    instCfg.configPath = printerCfgPath;
    instCfg.firmwareVersion = "tether-sim-1.0.0";

    KlippyInstance inst(instCfg);
    auto& server = inst.server();
    server.loadConfigFile(printerCfgPath);

    // Populate gcode.commands with help text for Mainsail's macro/gcode UI.
    if (auto gcodeObj = inst.gcodeObject()) {
        gcodeObj->setCommands(getGcodeHelpJson().asObject());
    }

    // ------------------------------------------------------------------
    // Step 2: Wire simulated thermal plants (extruder + bed)
    // ------------------------------------------------------------------
    // Extruder hotend: small thermal mass, ~50W heater, reaches 250°C.
    //   Time constant ≈ R_th * C_th = 5.0 * 10 = 50 s
    //   Steady-state at full power: T_amb + eta * P * R = 25 + 0.9*50*5 = 250°C
    auto extruderPlant = std::make_shared<ThermalPlant>(
        10.0, 5.0, 0.9, 25.0, 50.0, simDt);

    // Heater bed: larger thermal mass, ~150W heater, reaches ~90°C.
    //   Time constant ≈ 0.5 * 200 = 100 s
    //   Steady-state at full power: 25 + 0.9*150*0.5 = 92.5°C
    auto bedPlant = std::make_shared<ThermalPlant>(
        200.0, 0.5, 0.9, 25.0, 150.0, simDt);

    // Create Heater objects.  The sensor reads from the plant temperature;
    // the PWM write stores the duty cycle for the next plant step.
    auto extruderHeater = std::make_shared<Heater>(
        0,
        [extruderPlant](double pwm) { extruderPlant->pwm = pwm; },
        [extruderPlant]() { return extruderPlant->temp; });
    extruderHeater->setPIDParams({14.0, 0.1, 50.0, 100.0, 0.0, 1.0});
    extruderHeater->setControlInterval(simDt);

    auto bedHeater = std::make_shared<Heater>(
        1,
        [bedPlant](double pwm) { bedPlant->pwm = pwm; },
        [bedPlant]() { return bedPlant->temp; });
    bedHeater->setPIDParams({10.0, 0.05, 30.0, 100.0, 0.0, 1.0});
    bedHeater->setControlInterval(simDt);

    // Wire heaters into the instance.  setExtruderHeater refreshes the
    // extruder printer object automatically; setHeaterBed does NOT, so we
    // recreate the heater_bed object manually.
    inst.setExtruderHeater(extruderHeater);
    inst.setHeaterBed(bedHeater);
    auto newBedObj = std::make_shared<HeaterBedObject>(bedHeater);
    server.unregisterObject("heater_bed");
    server.registerObject(newBedObj);

    // ------------------------------------------------------------------
    // Step 3: Wire fan, probe, and endstops
    // ------------------------------------------------------------------
    auto fan = std::make_shared<Fan>(2, [](double) {});
    inst.setFan(fan);

    auto probe = std::make_shared<Probe>(3, []() { return false; });
    inst.setProbe(probe);

    auto xEndstop = std::make_shared<Endstop>(4, []() { return false; });
    auto yEndstop = std::make_shared<Endstop>(5, []() { return false; });
    auto zEndstop = std::make_shared<Endstop>(6, []() { return false; });
    inst.setEndstop("x", xEndstop);
    inst.setEndstop("y", yEndstop);
    inst.setEndstop("z", zEndstop);

    // ------------------------------------------------------------------
    // Step 4: Set initial printer state
    // ------------------------------------------------------------------
    server.setState(PrinterState::Ready, "Tether simulated printer is ready");
    // Axes start unhomed — user must run G28 to home them.
    // The toolhead is physically at the centre of the bed (150, 150) and
    // 25 mm above the bed (Z=0).  G28 will move from here to the endstops.
    inst.toolheadObject()->setHomedAxes("");
    inst.setToolheadPosition({150.0, 150.0, 25.0, 0.0});
    inst.toolheadObject()->setStatus("Idle");
    inst.toolheadObject()->setMaxVelocity(3000.0);
    inst.toolheadObject()->setMaxAccel(3000.0);
    inst.toolheadObject()->setMaxAccelToDecel(1500.0);
    inst.mcuObject()->setMcuVersion("tether-sim-mcu-1.0.0");
    inst.mcuObject()->setFreq(180000000);

    // Register power devices for Mainsail display.
    // No webcam registered — there's no actual camera stream, and a fake URL
    // causes "Failed to fetch" errors in the browser.
    server.registerPowerDevice("printer", "on");
    server.registerPowerDevice("lights", "off");

    server.emitGcodeResponse("// Tether simulated printer started");
    server.emitGcodeResponse("// Send G-code from Mainsail console or start a print from the file browser.");

    std::printf("KlippyServer created with %zu endpoints and %zu objects\n",
                server.listEndpoints().size(),
                server.listObjects().size());
    std::fflush(stdout);

    // ------------------------------------------------------------------
    // Step 5: Override print-start endpoints to select the file first.
    //
    // The default print-start handler calls sdcard_->startPrint() but does
    // not select the file (the handler signature has no filename parameter).
    // Mainsail sends the filename via POST /printer/print/start?filename=...
    // so we override the endpoint to extract it, call selectFile(), then
    // startPrint().
    // ------------------------------------------------------------------
    auto& sdcard = inst.sdcard();
    auto printStats = inst.printStatsObject();
    auto idleTimeout = inst.idleTimeoutObject();
    auto toolhead = inst.toolheadObject();
    auto displayStatus = inst.displayStatusObject();

    auto handlePrintStartWithFile = [&server, &sdcard, printStats,
                                     idleTimeout](const JsonValue& params) {
        std::string filename;
        if (params.isObject()) {
            auto* fn = params.find("filename");
            if (fn && fn->isString()) filename = fn->asString();
        }
        if (!filename.empty()) {
            sdcard.selectFile(filename);
            printStats->setFilename(filename);
        }
        sdcard.startPrint();
        printStats->setState("printing");
        idleTimeout->setState("Printing");
        server.setState(PrinterState::Printing,
                        filename.empty() ? "Print started"
                                         : "Printing: " + filename);
        std::map<std::string, JsonValue> result;
        result["result"] = JsonValue("ok");
        return JsonValue(result);
    };
    server.registerEndpoint("printer/start", handlePrintStartWithFile);
    server.registerEndpoint("printer/print/start", handlePrintStartWithFile);

    // ------------------------------------------------------------------
    // Step 6: Create the HTTP/WebSocket transport (shares KlippyServer)
    // ------------------------------------------------------------------
    HttpServerConfig httpCfg;
    httpCfg.port = port;
    httpCfg.apiKey = apiKey;
    httpCfg.requireAuth = requireAuth;
    httpCfg.gcodesRoot = gcodesRoot;
    httpCfg.configRoot = configRoot;
    httpCfg.logsRoot = logsRoot;
    httpCfg.webRoot = webRoot;
    httpCfg.trustedClients = {"127.0.0.1", "::1",
                              "172.16.0.0/12", "192.168.0.0/16"};

    auto httpServer = std::make_shared<KlippyHttpServer>(server, httpCfg);

    // ------------------------------------------------------------------
    // Step 7: Start UDS (if --with-moonraker) + HTTP
    // ------------------------------------------------------------------
    if (withMoonraker) {
        if (!inst.start()) {
            std::fprintf(stderr, "Failed to start UDS transport at %s\n",
                         udsPath.c_str());
            return 1;
        }
        std::printf("UDS transport listening at %s\n", udsPath.c_str());
    }

    if (!httpServer->start()) {
        std::fprintf(stderr, "Failed to start HTTP server on port %u\n", port);
        if (withMoonraker) inst.stop();
        return 1;
    }
    std::printf("HTTP/WebSocket server listening on port %u\n", port);
    if (!webRoot.empty()) {
        std::printf("Serving web UI static assets from %s\n", webRoot.c_str());
        std::printf("\nOpen http://localhost:%u/ in a browser.\n", port);
    } else {
        std::printf("\nNo web UI configured. Use --mainsail DIR or --fluidd DIR\n");
        std::printf("to auto-clone and build a web UI, or --web-root DIR to\n");
        std::printf("serve pre-built static assets.\n");
        std::printf("\nRaw API available at http://localhost:%u/\n", port);
    }
    std::printf("\nPress Ctrl+C to stop.\n\n");
    std::fflush(stdout);

    // ------------------------------------------------------------------
    // Step 8: Simulation thread (std::jthread for cooperative cancellation)
    //
    // Runs two loops at the configured tick rate:
    //   - Thermal: step the oven plants and run heater PID control
    //   - Print: stream G-code lines from the virtual SD card and execute
    //             them, updating print stats and toolhead position
    // ------------------------------------------------------------------
    std::jthread simThread([&](std::stop_token st) {
        const auto tickDur = std::chrono::milliseconds(simTickMs);
        auto lastTick = std::chrono::steady_clock::now();
        auto printStartTime = std::chrono::steady_clock::now();
        bool wasPrinting = false;
        int tickCount = 0;

        // Print streaming: execute a few G-code lines per tick so the
        // toolhead position animates smoothly in the Mainsail dashboard.
        const int linesPerTick = 2;

        while (!st.stop_requested()) {
            std::this_thread::sleep_for(tickDur);
            auto now = std::chrono::steady_clock::now();
            double elapsed = std::chrono::duration<double>(now - lastTick).count();
            lastTick = now;
            tickCount++;

            // --- Thermal simulation ---
            {
                std::lock_guard<std::recursive_mutex> lock(inst.mutex());
                extruderHeater->control();  // PID reads temp, writes PWM
                extruderPlant->step();      // Advance plant by dt

                bedHeater->control();
                bedPlant->step();

                // Record temperatures for the Mainsail temperature graph
                // (server/temperature_store endpoint).
                server.recordTemperature("extruder",
                                         extruderHeater->currentTemp(),
                                         extruderHeater->target());
                server.recordTemperature("heater_bed",
                                         bedHeater->currentTemp(),
                                         bedHeater->target());
            }

            // --- Print simulation ---
            {
                std::lock_guard<std::recursive_mutex> lock(inst.mutex());

                bool isActive = sdcard.isActive();
                bool isPaused = sdcard.isPaused();

                if (isActive && !isPaused) {
                    if (!wasPrinting) {
                        printStartTime = std::chrono::steady_clock::now();
                        wasPrinting = true;
                        toolhead->setStatus("Printing");
                    }

                    // Stream a few G-code lines from the file
                    auto lines = sdcard.readChunk(linesPerTick);
                    for (const auto& line : lines) {
                        if (line.empty() || line[0] == ';') continue;
                        inst.executeGcode(line);
                    }

                    // Update print statistics
                    double printDur =
                        std::chrono::duration<double>(
                            now - printStartTime).count();
                    printStats->setPrintDuration(printDur);
                    printStats->setTotalDuration(printDur);
                    double progress = sdcard.progress();
                    printStats->setProgress(progress);
                    displayStatus->setProgress(progress);

                    // Estimate filament used from progress
                    // (sample file extrudes ~35 mm per side × 4 × 100 layers)
                    const double nominalFilamentMm = 14000.0;
                    printStats->setFilamentUsed(progress * nominalFilamentMm);

                    // Update layer info
                    int currentLayer = static_cast<int>(progress * 100.0);
                    printStats->setInfoTotalLayer(100);
                    printStats->setInfoCurrentLayer(
                        std::min(currentLayer + 1, 100));

                    // Check for print completion (sdcard went inactive
                    // after being active — EOF reached).
                    if (!sdcard.isActive()) {
                        printStats->setState("complete");
                        printStats->setProgress(1.0);
                        displayStatus->setProgress(1.0);
                        toolhead->setStatus("Idle");
                        idleTimeout->setState("Ready");
                        server.setState(PrinterState::Ready,
                                        "Print complete");
                        server.emitGcodeResponse(
                            "// Print complete: " + sdcard.filePath());
                        wasPrinting = false;
                    }
                } else if (wasPrinting && !isActive) {
                    // Print was cancelled or completed externally
                    wasPrinting = false;
                    toolhead->setStatus("Idle");
                }
            }

            // --- System stats (every 5 ticks = ~0.5 s) ---
            if (tickCount % 5 == 0) {
                std::lock_guard<std::recursive_mutex> lock(inst.mutex());
                inst.updateSystemStats();
                // Simulate MCU byte counters
                inst.updateMcuStats(
                    1000 + tickCount * 10,
                    500 + tickCount * 5,
                    0,
                    0.002);
            }
        }
    });

    // ------------------------------------------------------------------
    // Step 9: Wait for SIGINT/SIGTERM via sigwait (synchronous, no handler).
    // SIGINT/SIGTERM are blocked in all threads, so Drogon's handler never
    // fires.  sigwait blocks the main thread until a signal arrives, then
    // we shut down cleanly.
    // ------------------------------------------------------------------
    int sig = 0;
    sigwait(&mask, &sig);

    std::printf("\nShutting down (received signal %d)...\n", sig);
    simThread.request_stop();
    simThread.join();
    httpServer->stop();
    if (withMoonraker) inst.stop();
    std::printf("Done.\n");

    return 0;
}
