/**
 * @file RoundedSquareGCodeTest.cpp
 * @brief End-to-end test: manufactured G-code → parse → NURBS → ParetoPlanner → WSS validation.
 *
 * @details
 * This test manufactures a G-code program that mimics the structure of real
 * 3D-printer output (rounded square shell with Z-hop "perimeter puncture"
 * patterns, straight grid infill, multiple layers, rapid travel moves,
 * different feed rates for shell vs infill). It then runs the full pipeline:
 *
 *   G-code text → PlanningSegmentBuilder → piecewiseNurbsFromSegments
 *               → PathAdapter (with per-segment feed rates + corner velocities)
 *               → ParetoTimeEnergyOptimalVelocityPlanner
 *               → WSS (Weighted Switching Structure)
 *
 * The WSS is validated for:
 *   - Arc length continuity
 *   - Time continuity
 *   - Velocity continuity (no GAPs)
 *   - Acceleration limit satisfaction
 *   - Jerk limit satisfaction
 *   - Start/end velocity = 0
 *   - Non-negative velocities
 *   - Velocity limit satisfaction at sampled points
 *
 * This is a regression test for the coalescing bug where BANG arcs with
 * different a0 values were merged, producing velocity discontinuities,
 * and for the acceleration-limit violation where the solver applied jerk
 * that pushed acceleration beyond the bounds.
 */

#include <gtest/gtest.h>

#include "tether/gcode/PlanningSegmentBuilder.hpp"
#include "tether/motion_planner/geometry/PlanningSegmentConverter.hpp"
#include "tether/motion_planner/PathAdapter.hpp"
#include "tether/motion_planner/analytical/ParetoTimeEnergyOptimalVelocityPlanner.hpp"

#include <cmath>
#include <random>
#include <set>
#include <sstream>
#include <string>
#include <vector>

using namespace MotionPlanner;
using namespace MotionPlanner::analytical;
using GCode::PlanningSegment;
using tether::motion::piecewiseNurbsFromSegments;

namespace {

/// Generate a rounded-square G-code program with shell + grid infill.
///
/// @param numLayers    Number of print layers
/// @param size         Square side length (mm)
/// @param shellLoops   Number of perimeter/shell loops
/// @param infillSpacing Distance between infill lines (mm)
/// @return G-code text
std::string generateRoundedSquareGcode(int numLayers, double size,
                                       int shellLoops, double infillSpacing) {
    std::ostringstream os;

    // Feed rates (mm/min, as in real G-code)
    const int F_TRAVEL = 18000;
    const int F_PERIMETER = 14400;
    const int F_INFILL = 2400;
    const int F_ZMOVE = 1200;
    const int F_PUNCTURE = 240;

    const double layerHeight = 0.3;
    const double cornerRadius = std::min(10.0, size * 0.1);
    const double shellInset = 2.0;

    // Header
    os << "; Generated by RoundedSquareGCodeTest\n";
    os << "G21 ; set units to mm\n";
    os << "G90 ; absolute XYZ positioning\n";
    os << "G92 E0 ; reset extrusion distance\n";
    os << "G28 ; home all axes\n";

    for (int layer = 0; layer < numLayers; ++layer) {
        double z = layerHeight * (layer + 1);
        os << "; Layer " << layer << "\n";
        os << "G0 Z" << z << " F" << F_ZMOVE << "\n";

        // --- Shell loops ---
        for (int loop = 0; loop < shellLoops; ++loop) {
            double r = std::max(1.0, cornerRadius - loop * shellInset * 0.5);
            double s = std::max(10.0, size - loop * shellInset * 2);

            // Generate rounded square points (CCW)
            // Corner centers
            struct Pt { double x, y; };
            double half = s / 2.0;
            Pt centers[] = {
                {half - r, half - r},  // bottom-left
                {half + s - r - half, half - r},  // bottom-right → (s/2 + s/2 - r, s/2 - r) = (s-r, s/2-r)
            };
            // Simpler: just use 4 corners with arcs
            // Bottom-left center: (r, r), start angle 180
            // Bottom-right center: (s-r, r), start angle 270
            // Top-right center: (s-r, s-r), start angle 0
            // Top-left center: (r, s-r), start angle 90
            Pt cornerCenters[] = {
                {r, r},
                {s - r, r},
                {s - r, s - r},
                {r, s - r},
            };
            double startAngles[] = {180.0, 270.0, 0.0, 90.0};

            std::vector<Pt> pts;
            const int segPerCorner = 8;
            for (int c = 0; c < 4; ++c) {
                double a0 = startAngles[c] * M_PI / 180.0;
                double a1 = a0 + M_PI / 2.0;
                for (int j = 0; j < segPerCorner; ++j) {
                    double t = static_cast<double>(j) / segPerCorner;
                    double a = a0 + t * (a1 - a0);
                    pts.push_back({cornerCenters[c].x + r * std::cos(a),
                                   cornerCenters[c].y + r * std::sin(a)});
                }
            }
            pts.push_back(pts[0]);  // close loop

            // Travel to start
            os << "G0 X" << pts[0].x << " Y" << pts[0].y
               << " F" << F_TRAVEL << "\n";

            // Z-hop perimeter puncture
            os << "G1 Z" << (z - 0.4) << " F" << F_PUNCTURE << " ; perimeter puncture\n";
            os << "G1 Z" << z << " F" << F_PUNCTURE << "\n";

            // Extrude around shell
            for (size_t i = 1; i < pts.size(); ++i) {
                double dx = pts[i].x - pts[i-1].x;
                double dy = pts[i].y - pts[i-1].y;
                double e = 0.05 * std::hypot(dx, dy);
                os << "G1 X" << pts[i].x << " Y" << pts[i].y
                   << " E" << e << " F" << F_PERIMETER << "\n";

                // Insert perimeter puncture every 8 segments
                if (i % 8 == 0 && i < pts.size() - 1) {
                    os << "G1 Z" << (z - 0.4) << " F" << F_PUNCTURE
                       << " ; perimeter puncture\n";
                    os << "G1 Z" << z << " F" << F_PUNCTURE << "\n";
                }
            }
        }

        // --- Grid infill (X direction) ---
        double xStart = cornerRadius;
        double xEnd = size - cornerRadius;
        double yStart = cornerRadius;
        double yEnd = size - cornerRadius;

        int lineIdx = 0;
        for (double y = yStart; y <= yEnd + 0.01; y += infillSpacing) {
            if (lineIdx % 2 == 0) {
                os << "G0 X" << xStart << " Y" << y << " F" << F_TRAVEL << "\n";
                double e = 0.05 * (xEnd - xStart);
                os << "G1 X" << xEnd << " Y" << y << " E" << e
                   << " F" << F_INFILL << "\n";
            } else {
                os << "G0 X" << xEnd << " Y" << y << " F" << F_TRAVEL << "\n";
                double e = 0.05 * (xEnd - xStart);
                os << "G1 X" << xStart << " Y" << y << " E" << e
                   << " F" << F_INFILL << "\n";
            }
            ++lineIdx;
        }

        // --- Grid infill (Y direction) ---
        lineIdx = 0;
        for (double x = xStart; x <= xEnd + 0.01; x += infillSpacing) {
            if (lineIdx % 2 == 0) {
                os << "G0 X" << x << " Y" << yStart << " F" << F_TRAVEL << "\n";
                double e = 0.05 * (yEnd - yStart);
                os << "G1 X" << x << " Y" << yEnd << " E" << e
                   << " F" << F_INFILL << "\n";
            } else {
                os << "G0 X" << x << " Y" << yEnd << " F" << F_TRAVEL << "\n";
                double e = 0.05 * (yEnd - yStart);
                os << "G1 X" << x << " Y" << yStart << " E" << e
                   << " F" << F_INFILL << "\n";
            }
            ++lineIdx;
        }
    }

    os << "; End of G-code\n";
    os << "M84 ; disable motors\n";
    return os.str();
}

/// Compute the end velocity of an arc from its parameters.
double arcEndVelocity(const WeightedArc& a) {
    if (a.type == WeightedArcType::DWELL) return 0.0;
    if (a.type == WeightedArcType::SINGULAR) {
        return a.v0 + a.a_star * a.duration;
    } else if (a.type == WeightedArcType::WALL) {
        return a.v0;
    } else {
        return a.v0 + a.a0 * a.duration
             + 0.5 * a.eta * a.duration * a.duration;
    }
}

/// Compute the end acceleration of an arc.
double arcEndAcceleration(const WeightedArc& a) {
    if (a.type == WeightedArcType::DWELL) return 0.0;
    if (a.type == WeightedArcType::SINGULAR) {
        return a.a_star;
    } else if (a.type == WeightedArcType::WALL) {
        return 0.0;
    } else {
        return a.a0 + a.eta * a.duration;
    }
}

} // anonymous namespace

// ============================================================================
// Test: Full pipeline on manufactured rounded-square G-code
// ============================================================================
//
// This test validates that the ParetoTimeEnergyOptimalVelocityPlanner
// produces a physically valid WSS for a G-code program that mimics real
// 3D-printer output. The G-code includes:
//   - Multiple layers with Z moves
//   - Rounded square shell with Z-hop "perimeter puncture" patterns
//   - Straight grid infill at a different (slower) feed rate
//   - Rapid travel moves between shell and infill
//
// The test checks:
//   1. The G-code parses successfully (non-zero segments)
//   2. The NURBS path is built (non-zero pieces)
//   3. The planner produces a velocity profile (non-null)
//   4. The WSS has no velocity discontinuities (GAPs)
//   5. The WSS has no acceleration limit violations
//   6. The WSS has no jerk limit violations
//   7. Start and end velocities are zero
//   8. All velocities are non-negative
//   9. Arc length continuity (s1[i] == s0[i+1])
//  10. Time continuity (t0[i] + dur[i] == t0[i+1])

TEST(RoundedSquareGCodeTest, FullPipeline_ProducesValidWSS) {
    // Generate G-code for a small rounded square (3 layers, 50mm)
    std::string gcode = generateRoundedSquareGcode(3, 50.0, 2, 5.0);
    ASSERT_FALSE(gcode.empty());

    // Step 1: Parse G-code
    auto parseResult = GCode::PlanningSegmentBuilder::fromText(gcode);
    ASSERT_TRUE(parseResult.error.ok()) << "G-code parsing failed";
    auto& segments = parseResult.segments;
    ASSERT_GT(segments.size(), 10u) << "Too few segments parsed";

    // Step 2: Build NURBS path
    auto nurbsResult = piecewiseNurbsFromSegments(segments);
    ASSERT_GT(nurbsResult.path.numPieces(), 0u) << "No NURBS pieces created";
    ASSERT_GT(nurbsResult.path.totalLength(), 100.0)
        << "Path too short: " << nurbsResult.path.totalLength();

    // Step 3: Build PathAdapter with per-segment feed rates + corner velocities
    PathAdapter<3, double> pathAdapter(nurbsResult.path);
    if (!nurbsResult.feedRates.empty()) {
        pathAdapter.setSegmentVelocityLimits(nurbsResult.feedRates);
        pathAdapter.computeCornerVelocities(0.05, 2000.0);
    }

    // Step 4: Run ParetoPlanner
    KinematicLimits<3, double> limits;
    limits.path.maxPathVelocity = 200.0;
    limits.path.maxPathAcceleration = 2000.0;
    limits.path.maxPathJerk = 20000.0;
    limits.path.jerkLimitEnabled = true;
    limits.path.maxCentripetalAcceleration = 2000.0;
    for (int i = 0; i < 3; ++i) {
        limits.axis.maxVelocity[i] = 200.0;
        limits.axis.maxAcceleration[i] = 2000.0;
        limits.axis.maxJerk[i] = 20000.0;
    }
    limits.axis.jerkLimitEnabled = true;

    double feedRate = 200.0;
    std::size_t numSamples = std::min<std::size_t>(
        20000, std::max<std::size_t>(200, pathAdapter.numSegments() * 20));

    ParetoTimeEnergyOptimalVelocityPlanner<3, double> profiler(limits);
    auto velocityProfile = profiler.computeProfile(
        pathAdapter, feedRate, 0.0, 0.0, numSamples);
    ASSERT_NE(velocityProfile, nullptr) << "Planner returned null profile";

    // Step 5: Extract WSS
    auto wss = profiler.weightedSource();
    ASSERT_NE(wss, nullptr) << "weightedSource() returned null";
    const auto& arcs = wss->arcs();
    ASSERT_GT(arcs.size(), 10u) << "Too few arcs in WSS";

    // ── Validation ──────────────────────────────────────────────────────

    // 1. Arc length continuity: s1[i] == s0[i+1]
    for (size_t i = 1; i < arcs.size(); ++i) {
        double gap = std::abs(arcs[i].s0 - arcs[i-1].s1);
        EXPECT_LT(gap, 1e-6) << "Arc length discontinuity at arc " << i;
    }

    // 2. Time continuity: t0[i] + dur[i] == t0[i+1]
    for (size_t i = 1; i < arcs.size(); ++i) {
        double prevEnd = arcs[i-1].t0 + arcs[i-1].duration;
        double gap = std::abs(arcs[i].t0 - prevEnd);
        EXPECT_LT(gap, 1e-6) << "Time discontinuity at arc " << i;
    }

    // 3. Velocity continuity: vEnd[i] == v0[i+1] (no GAPs)
    //    Tolerance: 1e-3 mm/s (accounts for floating-point accumulation)
    double maxVelGap = 0.0;
    for (size_t i = 1; i < arcs.size(); ++i) {
        double prevVEnd = arcEndVelocity(arcs[i-1]);
        double gap = std::abs(arcs[i].v0 - prevVEnd);
        if (gap > maxVelGap) maxVelGap = gap;
        EXPECT_LT(gap, 1e-3)
            << "Velocity GAP at arc " << i
            << ": prevVEnd=" << prevVEnd
            << " currV0=" << arcs[i].v0
            << " gap=" << gap;
    }

    // 4. Acceleration limit: |a0| and |aEnd| <= maxAccel for all arcs
    double maxAccel = 2000.0;
    double maxAccelSeen = 0.0;
    for (size_t i = 0; i < arcs.size(); ++i) {
        double aEnd = arcEndAcceleration(arcs[i]);
        EXPECT_LE(std::abs(arcs[i].a0), maxAccel + 1e-3)
            << "Acceleration limit violated at arc " << i
            << " a0=" << arcs[i].a0;
        EXPECT_LE(std::abs(aEnd), maxAccel + 1e-3)
            << "Acceleration limit violated at arc " << i
            << " aEnd=" << aEnd;
        maxAccelSeen = std::max(maxAccelSeen, std::max(
            std::abs(arcs[i].a0), std::abs(aEnd)));
    }

    // 5. Jerk limit: |eta| <= maxJerk for all arcs
    double maxJerk = 20000.0;
    for (size_t i = 0; i < arcs.size(); ++i) {
        EXPECT_LE(std::abs(arcs[i].eta), maxJerk + 1e-3)
            << "Jerk limit violated at arc " << i
            << " eta=" << arcs[i].eta;
    }

    // 6. Start velocity = 0
    EXPECT_LT(std::abs(arcs.front().v0), 1e-3)
        << "Start velocity not zero: " << arcs.front().v0;

    // 7. End velocity = 0
    double endV = arcEndVelocity(arcs.back());
    EXPECT_LT(std::abs(endV), 1e-3)
        << "End velocity not zero: " << endV;

    // 8. Non-negative velocities
    for (size_t i = 0; i < arcs.size(); ++i) {
        EXPECT_GE(arcs[i].v0, -1e-6)
            << "Negative velocity at arc " << i << ": " << arcs[i].v0;
        double vEnd = arcEndVelocity(arcs[i]);
        EXPECT_GE(vEnd, -1e-6)
            << "Negative end velocity at arc " << i << ": " << vEnd;
    }

    // 9. Total arc length matches path
    double totalArcLen = arcs.back().s1 - arcs.front().s0;
    double pathLen = pathAdapter.totalLength();
    EXPECT_NEAR(totalArcLen, pathLen, 1.0)
        << "Total arc length doesn't match path length";

    // Print summary for debugging
    std::cout << "RoundedSquareGCodeTest summary:\n"
              << "  Segments: " << segments.size() << "\n"
              << "  NURBS pieces: " << nurbsResult.path.numPieces() << "\n"
              << "  Path length: " << pathLen << " mm\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  Total time: " << wss->totalTime() << " s\n"
              << "  Max velocity gap: " << maxVelGap << " mm/s\n"
              << "  Max acceleration seen: " << maxAccelSeen << " mm/s²\n";
}

// ============================================================================
// Test: Larger G-code (5 layers, 100mm) still produces valid WSS
// ============================================================================
//
// This is a stress test with a larger G-code program to ensure the planner
// handles the increased number of segments and corners without issues.

TEST(RoundedSquareGCodeTest, LargerGCode_ProducesValidWSS) {
    // Generate larger G-code (5 layers, 100mm, 3 shell loops)
    std::string gcode = generateRoundedSquareGcode(5, 100.0, 3, 5.0);
    ASSERT_FALSE(gcode.empty());

    // Parse
    auto parseResult = GCode::PlanningSegmentBuilder::fromText(gcode);
    ASSERT_TRUE(parseResult.error.ok()) << "G-code parsing failed";
    auto& segments = parseResult.segments;
    ASSERT_GT(segments.size(), 100u) << "Too few segments parsed";

    // Build NURBS path
    auto nurbsResult = piecewiseNurbsFromSegments(segments);
    ASSERT_GT(nurbsResult.path.numPieces(), 0u);

    // Build PathAdapter
    PathAdapter<3, double> pathAdapter(nurbsResult.path);
    if (!nurbsResult.feedRates.empty()) {
        pathAdapter.setSegmentVelocityLimits(nurbsResult.feedRates);
        pathAdapter.computeCornerVelocities(0.05, 2000.0);
    }

    // Run planner
    KinematicLimits<3, double> limits;
    limits.path.maxPathVelocity = 200.0;
    limits.path.maxPathAcceleration = 2000.0;
    limits.path.maxPathJerk = 20000.0;
    limits.path.jerkLimitEnabled = true;
    limits.path.maxCentripetalAcceleration = 2000.0;
    for (int i = 0; i < 3; ++i) {
        limits.axis.maxVelocity[i] = 200.0;
        limits.axis.maxAcceleration[i] = 2000.0;
        limits.axis.maxJerk[i] = 20000.0;
    }
    limits.axis.jerkLimitEnabled = true;

    double feedRate = 200.0;
    std::size_t numSamples = std::min<std::size_t>(
        20000, std::max<std::size_t>(200, pathAdapter.numSegments() * 20));

    ParetoTimeEnergyOptimalVelocityPlanner<3, double> profiler(limits);
    auto velocityProfile = profiler.computeProfile(
        pathAdapter, feedRate, 0.0, 0.0, numSamples);
    ASSERT_NE(velocityProfile, nullptr);

    auto wss = profiler.weightedSource();
    ASSERT_NE(wss, nullptr);
    const auto& arcs = wss->arcs();
    ASSERT_GT(arcs.size(), 50u);

    // Validate velocity continuity (no GAPs)
    for (size_t i = 1; i < arcs.size(); ++i) {
        double prevVEnd = arcEndVelocity(arcs[i-1]);
        double gap = std::abs(arcs[i].v0 - prevVEnd);
        EXPECT_LT(gap, 1e-3)
            << "Velocity GAP at arc " << i
            << ": prevVEnd=" << prevVEnd
            << " currV0=" << arcs[i].v0
            << " gap=" << gap;
    }

    // Validate acceleration limits
    for (size_t i = 0; i < arcs.size(); ++i) {
        double aEnd = arcEndAcceleration(arcs[i]);
        EXPECT_LE(std::abs(arcs[i].a0), 2000.0 + 1e-3)
            << "Accel limit violated at arc " << i << " a0=" << arcs[i].a0;
        EXPECT_LE(std::abs(aEnd), 2000.0 + 1e-3)
            << "Accel limit violated at arc " << i << " aEnd=" << aEnd;
    }

    // Validate jerk limits
    for (size_t i = 0; i < arcs.size(); ++i) {
        EXPECT_LE(std::abs(arcs[i].eta), 20000.0 + 1e-3)
            << "Jerk limit violated at arc " << i;
    }

    // Start/end velocity = 0
    EXPECT_LT(std::abs(arcs.front().v0), 1e-3);
    double endV = arcEndVelocity(arcs.back());
    EXPECT_LT(std::abs(endV), 1e-3);

    std::cout << "LargerGCode summary:\n"
              << "  Segments: " << segments.size() << "\n"
              << "  NURBS pieces: " << nurbsResult.path.numPieces() << "\n"
              << "  Path length: " << pathAdapter.totalLength() << " mm\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  Total time: " << wss->totalTime() << " s\n";
}

// ============================================================================
// Dwell tests: G4 commands inserted at random points
// ============================================================================
//
// These tests insert G4 dwell commands at various points in the G-code
// and verify that:
//   1. The dwell causes a proper stop & start (v=0 at the dwell point)
//   2. No constraint violations occur during the stop & start
//   3. The dwell time is respected (included in total trajectory time)
//   4. The WSS contains DWELL arcs at the correct positions

/// Generate a simple square G-code with dwells inserted at random points.
///
/// @param size         Square side length (mm)
/// @param numDwells    Number of dwells to insert
/// @param dwellMs      Dwell duration (milliseconds, G4 P parameter)
/// @param seed         Random seed for reproducibility
/// @return Pair of (G-code text, list of dwell positions in G-code line order)
struct DwellInsertion {
    int lineIndex;      // Which motion line the dwell was inserted after
    double dwellSec;    // Dwell duration in seconds
};

std::pair<std::string, std::vector<DwellInsertion>>
generateSquareWithDwells(double size, int numDwells, double dwellMs,
                         unsigned seed) {
    std::mt19937 rng(seed);
    std::ostringstream os;

    // Generate the 4 sides of a square
    struct Move { double x, y; int feed; };
    std::vector<Move> moves = {
        {size, 0,    3000},   // bottom edge
        {size, size, 3000},   // right edge
        {0,    size, 3000},   // top edge
        {0,    0,    3000},   // left edge (back to start)
    };

    // Build the G-code, inserting dwells at random points
    os << "G21\nG90\nG92 E0\n";

    std::vector<DwellInsertion> insertions;
    double curX = 0, curY = 0;
    int lineIdx = 0;

    // Travel to start
    os << "G0 X0 Y0 F18000\n"; lineIdx++;

    // Decide at which move indices to insert dwells
    std::set<int> dwellAfterMove;
    std::uniform_int_distribution<int> dist(0, 3);
    for (int i = 0; i < numDwells; ++i) {
        dwellAfterMove.insert(dist(rng));
    }

    for (int i = 0; i < 4; ++i) {
        // Extrude to the corner
        double dx = moves[i].x - curX;
        double dy = moves[i].y - curY;
        double e = 0.05 * std::hypot(dx, dy);
        os << "G1 X" << moves[i].x << " Y" << moves[i].y
           << " E" << e << " F" << moves[i].feed << "\n";
        lineIdx++;
        curX = moves[i].x;
        curY = moves[i].y;

        // Insert dwell if scheduled after this move
        if (dwellAfterMove.count(i)) {
            os << "G4 P" << dwellMs << " ; dwell\n";
            insertions.push_back({lineIdx, dwellMs / 1000.0});
            lineIdx++;
        }
    }

    os << "M84\n";
    return {os.str(), insertions};
}

/// Run the full pipeline on G-code with dwells and validate.
/// Returns the WSS and dwell point info for inspection.
struct DwellTestResult {
    std::shared_ptr<WeightedSwitchingStructure<3, double>> wss;
    std::vector<tether::motion::DwellPoint> dwellPoints;
    double pathLength;
    int numSegments;
};

DwellTestResult runDwellPipeline(const std::string& gcode) {
    DwellTestResult result;

    try {
        // Parse
        auto parseResult = GCode::PlanningSegmentBuilder::fromText(gcode);
        if (!parseResult.error.ok()) return result;
        auto& segments = parseResult.segments;

        // Build NURBS path (with dwell points)
        auto nurbsResult = piecewiseNurbsFromSegments(segments);
        result.pathLength = nurbsResult.path.totalLength();
        result.numSegments = static_cast<int>(nurbsResult.path.numPieces());
        result.dwellPoints = nurbsResult.dwellPoints;

    // Build PathAdapter
    PathAdapter<3, double> pathAdapter(nurbsResult.path);
    if (!nurbsResult.feedRates.empty()) {
        pathAdapter.setSegmentVelocityLimits(nurbsResult.feedRates);
        pathAdapter.computeCornerVelocities(0.05, 2000.0);
    }
    // Set dwell points (forces v=0 at those positions)
    if (!nurbsResult.dwellPoints.empty()) {
        std::vector<std::pair<double, double>> dwells;
        for (const auto& dp : nurbsResult.dwellPoints) {
            dwells.push_back({dp.arcLength, dp.duration});
        }
        pathAdapter.setDwellPoints(dwells);
    }

    // Run planner
    KinematicLimits<3, double> limits;
    limits.path.maxPathVelocity = 200.0;
    limits.path.maxPathAcceleration = 2000.0;
    limits.path.maxPathJerk = 20000.0;
    limits.path.jerkLimitEnabled = true;
    limits.path.maxCentripetalAcceleration = 2000.0;
    for (int i = 0; i < 3; ++i) {
        limits.axis.maxVelocity[i] = 200.0;
        limits.axis.maxAcceleration[i] = 2000.0;
        limits.axis.maxJerk[i] = 20000.0;
    }
    limits.axis.jerkLimitEnabled = true;

    double feedRate = 200.0;
    std::size_t numSamples = std::min<std::size_t>(
        20000, std::max<std::size_t>(200, pathAdapter.numSegments() * 20));

    ParetoTimeEnergyOptimalVelocityPlanner<3, double> profiler(limits);
        auto profile = profiler.computeProfile(pathAdapter, feedRate, 0.0, 0.0, numSamples);
        if (!profile) return result;

        result.wss = profiler.weightedSource();
    } catch (const std::exception& e) {
        // NURBS conversion or planner may throw for degenerate paths
        // (e.g. no motion segments). Return empty result.
        std::cout << "runDwellPipeline exception: " << e.what() << "\n";
    }
    return result;
}

TEST(RoundedSquareGCodeTest, Dwell_StopsAndStartsAtDwellPoint) {
    // Generate a 100mm square with 2 dwells (500ms each) at random points
    auto [gcode, insertions] = generateSquareWithDwells(100.0, 2, 500.0, 42);
    ASSERT_FALSE(gcode.empty());
    ASSERT_EQ(insertions.size(), 2u);

    auto result = runDwellPipeline(gcode);
    ASSERT_NE(result.wss, nullptr);
    ASSERT_EQ(result.dwellPoints.size(), 2u);

    const auto& arcs = result.wss->arcs();
    ASSERT_GT(arcs.size(), 10u);

    // Check that DWELL arcs exist in the WSS
    int dwellArcCount = 0;
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) {
            dwellArcCount++;
            // DWELL arc must have v=0, a=0, zero length
            EXPECT_NEAR(arc.v0, 0.0, 1e-10);
            EXPECT_NEAR(arc.a0, 0.0, 1e-10);
            EXPECT_NEAR(arc.s1 - arc.s0, 0.0, 1e-10);
            // Duration must match the dwell time
            EXPECT_NEAR(arc.duration, 0.5, 1e-6);  // 500ms = 0.5s
        }
    }
    EXPECT_EQ(dwellArcCount, 2)
        << "Expected 2 DWELL arcs in WSS, found " << dwellArcCount;

    // Check velocity continuity: v=0 at dwell boundaries
    // The arc before a DWELL must end with v=0, and the arc after must start with v=0
    for (size_t i = 0; i < arcs.size(); ++i) {
        if (arcs[i].type == WeightedArcType::DWELL) {
            // Check arc before: must end at v=0
            if (i > 0) {
                double prevVEnd = arcEndVelocity(arcs[i-1]);
                EXPECT_NEAR(prevVEnd, 0.0, 1e-3)
                    << "Arc before DWELL at index " << i
                    << " does not end at v=0 (got " << prevVEnd << ")";
            }
            // Check arc after: must start at v=0
            if (i + 1 < arcs.size()) {
                EXPECT_NEAR(arcs[i+1].v0, 0.0, 1e-3)
                    << "Arc after DWELL at index " << i
                    << " does not start at v=0 (got " << arcs[i+1].v0 << ")";
            }
        }
    }

    // Check no velocity GAPs (excluding DWELL arcs which are zero-length)
    for (size_t i = 1; i < arcs.size(); ++i) {
        if (arcs[i].type == WeightedArcType::DWELL) continue;
        if (arcs[i-1].type == WeightedArcType::DWELL) continue;
        double prevVEnd = arcEndVelocity(arcs[i-1]);
        double gap = std::abs(arcs[i].v0 - prevVEnd);
        EXPECT_LT(gap, 1e-3)
            << "Velocity GAP at arc " << i << ": " << gap;
    }

    // Check acceleration limits (DWELL arcs have a=0, so they're fine)
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) continue;
        double aEnd = arcEndAcceleration(arc);
        EXPECT_LE(std::abs(arc.a0), 2000.0 + 1e-3);
        EXPECT_LE(std::abs(aEnd), 2000.0 + 1e-3);
    }

    // Check jerk limits
    for (const auto& arc : arcs) {
        EXPECT_LE(std::abs(arc.eta), 20000.0 + 1e-3);
    }

    // Start/end velocity = 0
    EXPECT_NEAR(arcs.front().v0, 0.0, 1e-3);
    EXPECT_NEAR(arcEndVelocity(arcs.back()), 0.0, 1e-3);

    std::cout << "Dwell_StopsAndStarts summary:\n"
              << "  Path length: " << result.pathLength << " mm\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  DWELL arcs: " << dwellArcCount << "\n"
              << "  Total time: " << result.wss->totalTime() << " s\n"
              << "  Dwell points: " << result.dwellPoints.size() << "\n";
}

TEST(RoundedSquareGCodeTest, Dwell_DwellTimeRespectedInTotalTime) {
    // Generate a 50mm square with 3 dwells of varying durations
    // Use different durations to verify each is accounted for
    unsigned seed = 12345;
    std::mt19937 rng(seed);
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";

    // 4 edges with dwells after specific edges
    double size = 50.0;
    double dwellTimes[] = {0.250, 1.000, 0.500};  // seconds
    int dwellAfterEdge[] = {0, 2, 3};  // insert dwells after edges 0, 2, 3
    int dwellIdx = 0;

    double curX = 0, curY = 0;
    struct Move { double x, y; };
    Move moves[] = {{size, 0}, {size, size}, {0, size}, {0, 0}};

    for (int i = 0; i < 4; ++i) {
        double dx = moves[i].x - curX;
        double dy = moves[i].y - curY;
        double e = 0.05 * std::hypot(dx, dy);
        os << "G1 X" << moves[i].x << " Y" << moves[i].y
           << " E" << e << " F3000\n";
        curX = moves[i].x;
        curY = moves[i].y;

        if (dwellIdx < 3 && i == dwellAfterEdge[dwellIdx]) {
            // G4 P<ms>
            os << "G4 P" << static_cast<int>(dwellTimes[dwellIdx] * 1000)
               << " ; dwell\n";
            dwellIdx++;
        }
    }
    os << "M84\n";

    std::string gcode = os.str();
    auto result = runDwellPipeline(gcode);
    ASSERT_NE(result.wss, nullptr);
    ASSERT_EQ(result.dwellPoints.size(), 3u);

    // Verify dwell durations are correctly parsed
    EXPECT_NEAR(result.dwellPoints[0].duration, 0.250, 1e-6);
    EXPECT_NEAR(result.dwellPoints[1].duration, 1.000, 1e-6);
    EXPECT_NEAR(result.dwellPoints[2].duration, 0.500, 1e-6);

    // Total dwell time
    double totalDwellTime = 0.0;
    for (const auto& dp : result.dwellPoints) {
        totalDwellTime += dp.duration;
    }
    EXPECT_NEAR(totalDwellTime, 1.750, 1e-6);  // 0.25 + 1.0 + 0.5

    // The WSS total time must include the dwell time.
    // We verify this by checking that the total time is at least
    // the sum of dwell durations (the motion time is additional).
    double totalTime = result.wss->totalTime();
    EXPECT_GT(totalTime, totalDwellTime)
        << "Total time " << totalTime << " should exceed total dwell time "
        << totalDwellTime;

    // Count DWELL arcs and verify their durations
    const auto& arcs = result.wss->arcs();
    std::vector<double> dwellDurations;
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) {
            dwellDurations.push_back(arc.duration);
        }
    }
    ASSERT_EQ(dwellDurations.size(), 3u);
    // Durations should match (in order)
    EXPECT_NEAR(dwellDurations[0], 0.250, 1e-6);
    EXPECT_NEAR(dwellDurations[1], 1.000, 1e-6);
    EXPECT_NEAR(dwellDurations[2], 0.500, 1e-6);

    // The sum of all arc durations must equal the WSS total time
    double arcTimeSum = 0.0;
    for (const auto& arc : arcs) {
        arcTimeSum += arc.duration;
    }
    EXPECT_NEAR(arcTimeSum, totalTime, 1e-6);

    std::cout << "Dwell_DwellTimeRespected summary:\n"
              << "  Total time: " << totalTime << " s\n"
              << "  Total dwell time: " << totalDwellTime << " s\n"
              << "  Motion time: " << (totalTime - totalDwellTime) << " s\n"
              << "  DWELL arc durations: [" << dwellDurations[0] << ", "
              << dwellDurations[1] << ", " << dwellDurations[2] << "] s\n";
}

TEST(RoundedSquareGCodeTest, Dwell_MultipleRandomDwells_NoViolations) {
    // Complex rounded square with 5 random dwells inserted at random motion
    // lines. This tests that the planner handles a realistic multi-layer
    // G-code with corners, arcs, infill, and multiple v=0 dwell stops.
    std::string baseGcode = generateRoundedSquareGcode(3, 50.0, 2, 5.0);
    ASSERT_FALSE(baseGcode.empty());

    // Parse to get segment count
    auto parseResult = GCode::PlanningSegmentBuilder::fromText(baseGcode);
    ASSERT_TRUE(parseResult.error.ok());
    int numSegs = static_cast<int>(parseResult.segments.size());

    // Split into lines and find motion lines (G0/G1)
    std::vector<std::string> lines;
    {
        std::istringstream iss(baseGcode);
        std::string line;
        while (std::getline(iss, line)) lines.push_back(line);
    }
    std::vector<int> motionLineIndices;
    for (int i = 0; i < static_cast<int>(lines.size()); ++i) {
        size_t pos = lines[i].find_first_not_of(" \t");
        if (pos != std::string::npos && lines[i][pos] == 'G') {
            int gval = std::atoi(lines[i].c_str() + pos + 1);
            if (gval == 0 || gval == 1) motionLineIndices.push_back(i);
        }
    }
    ASSERT_GT(motionLineIndices.size(), 5u);

    // Insert 5 dwells at random motion lines (avoid first/last to leave room)
    std::mt19937 rng(99);
    int numDwells = 5;
    std::set<int> dwellLines;
    std::uniform_int_distribution<int> dist(
        1, static_cast<int>(motionLineIndices.size()) - 2);
    while (static_cast<int>(dwellLines.size()) < numDwells) {
        dwellLines.insert(motionLineIndices[dist(rng)]);
    }

    // Build modified G-code with dwells of random duration
    std::ostringstream modified;
    int dwellCount = 0;
    std::vector<double> dwellDurations;
    for (int i = 0; i < static_cast<int>(lines.size()); ++i) {
        modified << lines[i] << "\n";
        if (dwellLines.count(i)) {
            std::uniform_real_distribution<double> durDist(100.0, 2000.0);
            double dwellMs = durDist(rng);
            int dwellMsInt = static_cast<int>(dwellMs);
            modified << "G4 P" << dwellMsInt << " ; random dwell\n";
            dwellDurations.push_back(dwellMsInt / 1000.0);
            dwellCount++;
        }
    }
    ASSERT_EQ(dwellCount, numDwells);

    std::string modifiedGcode = modified.str();
    auto result = runDwellPipeline(modifiedGcode);
    ASSERT_NE(result.wss, nullptr)
        << "Planner returned null for rounded square with " << numDwells
        << " dwells";
    ASSERT_EQ(result.dwellPoints.size(), static_cast<size_t>(numDwells));

    const auto& arcs = result.wss->arcs();
    ASSERT_GT(arcs.size(), 10u);

    // Count DWELL arcs
    int dwellArcCount = 0;
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) dwellArcCount++;
    }
    EXPECT_EQ(dwellArcCount, numDwells);

    // Validate velocity continuity (no GAPs, excluding DWELL-to-arc boundaries
    // which are expected to be v=0 on both sides)
    for (size_t i = 1; i < arcs.size(); ++i) {
        if (arcs[i].type == WeightedArcType::DWELL) continue;
        if (arcs[i-1].type == WeightedArcType::DWELL) continue;
        double prevVEnd = arcEndVelocity(arcs[i-1]);
        double gap = std::abs(arcs[i].v0 - prevVEnd);
        EXPECT_LT(gap, 1e-3)
            << "Velocity GAP at arc " << i << ": " << gap;
    }

    // Validate acceleration limits
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) continue;
        double aEnd = arcEndAcceleration(arc);
        EXPECT_LE(std::abs(arc.a0), 2000.0 + 1e-3)
            << "Accel limit violated: a0=" << arc.a0;
        EXPECT_LE(std::abs(aEnd), 2000.0 + 1e-3)
            << "Accel limit violated: aEnd=" << aEnd;
    }

    // Validate jerk limits
    for (const auto& arc : arcs) {
        EXPECT_LE(std::abs(arc.eta), 20000.0 + 1e-3);
    }

    // Start/end velocity = 0
    EXPECT_NEAR(arcs.front().v0, 0.0, 1e-3);
    EXPECT_NEAR(arcEndVelocity(arcs.back()), 0.0, 1e-3);

    // Total time includes all dwell durations
    double totalDwellTime = 0.0;
    for (const auto& dp : result.dwellPoints) {
        totalDwellTime += dp.duration;
    }
    EXPECT_GT(result.wss->totalTime(), totalDwellTime);

    // Verify each dwell duration is respected
    for (size_t i = 0; i < result.dwellPoints.size(); ++i) {
        EXPECT_NEAR(result.dwellPoints[i].duration, dwellDurations[i], 1e-6);
    }

    std::cout << "Dwell_MultipleRandomDwells summary:\n"
              << "  Segments: " << numSegs << "\n"
              << "  Path length: " << result.pathLength << " mm\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  DWELL arcs: " << dwellArcCount << "\n"
              << "  Total time: " << result.wss->totalTime() << " s\n"
              << "  Total dwell time: " << totalDwellTime << " s\n";
}

TEST(RoundedSquareGCodeTest, Dwell_NoDwell_PipelineStillWorks) {
    // Sanity check: the same G-code without dwells should still work
    // and produce no DWELL arcs.
    std::string gcode = generateRoundedSquareGcode(2, 50.0, 1, 10.0);

    auto result = runDwellPipeline(gcode);
    ASSERT_NE(result.wss, nullptr);
    ASSERT_EQ(result.dwellPoints.size(), 0u);

    const auto& arcs = result.wss->arcs();
    int dwellArcCount = 0;
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) dwellArcCount++;
    }
    EXPECT_EQ(dwellArcCount, 0);

    // Standard validation
    for (size_t i = 1; i < arcs.size(); ++i) {
        double prevVEnd = arcEndVelocity(arcs[i-1]);
        double gap = std::abs(arcs[i].v0 - prevVEnd);
        EXPECT_LT(gap, 1e-3);
    }

    EXPECT_NEAR(arcs.front().v0, 0.0, 1e-3);
    EXPECT_NEAR(arcEndVelocity(arcs.back()), 0.0, 1e-3);
}

TEST(RoundedSquareGCodeTest, Dwell_ConsecutiveDwells_AllTracked) {
    // Test that multiple dwells at the same position (consecutive G4
    // commands) are all individually tracked as separate DWELL arcs.
    // The path is a simple straight line with 3 consecutive dwells
    // at the midpoint.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    os << "G1 X100 Y0 E5 F3000\n";
    // Three consecutive dwells at the same position
    os << "G4 P100\n";  // 0.1s
    os << "G4 P200\n";  // 0.2s
    os << "G4 P300\n";  // 0.3s
    os << "G1 X200 Y0 E5 F3000\n";

    auto result = runDwellPipeline(os.str());
    ASSERT_NE(result.wss, nullptr)
        << "Planner returned null for consecutive dwells";
    ASSERT_EQ(result.dwellPoints.size(), 3u)
        << "Expected 3 dwell points, got " << result.dwellPoints.size();

    const auto& arcs = result.wss->arcs();
    ASSERT_GT(arcs.size(), 5u);

    // Count DWELL arcs - should be exactly 3
    int dwellArcCount = 0;
    std::vector<double> dwellDurations;
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) {
            dwellArcCount++;
            dwellDurations.push_back(arc.duration);
            // Each DWELL arc must have v=0, a=0, zero length
            EXPECT_NEAR(arc.v0, 0.0, 1e-10);
            EXPECT_NEAR(arc.a0, 0.0, 1e-10);
            EXPECT_NEAR(arc.s1 - arc.s0, 0.0, 1e-10);
        }
    }
    EXPECT_EQ(dwellArcCount, 3)
        << "Expected 3 DWELL arcs, found " << dwellArcCount;

    // Verify each dwell duration is individually tracked
    ASSERT_EQ(dwellDurations.size(), 3u);
    EXPECT_NEAR(dwellDurations[0], 0.1, 1e-6);
    EXPECT_NEAR(dwellDurations[1], 0.2, 1e-6);
    EXPECT_NEAR(dwellDurations[2], 0.3, 1e-6);

    // Total dwell time = 0.1 + 0.2 + 0.3 = 0.6s
    double totalDwellTime = 0.1 + 0.2 + 0.3;
    EXPECT_GT(result.wss->totalTime(), totalDwellTime);

    // Start/end velocity = 0
    EXPECT_NEAR(arcs.front().v0, 0.0, 1e-3);
    EXPECT_NEAR(arcEndVelocity(arcs.back()), 0.0, 1e-3);

    std::cout << "Dwell_ConsecutiveDwells summary:\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  DWELL arcs: " << dwellArcCount << "\n"
              << "  Dwell durations: [" << dwellDurations[0] << ", "
              << dwellDurations[1] << ", " << dwellDurations[2] << "] s\n"
              << "  Total time: " << result.wss->totalTime() << " s\n";
}

TEST(RoundedSquareGCodeTest, Dwell_ManyDwells_NoSolverFailure) {
    // Test that the solver handles a large number of dwells, including
    // consecutive ones, without failing. Uses a long straight path with
    // dwells on every segment.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    int numSegments = 10;
    int numDwells = 0;
    for (int i = 0; i < numSegments; ++i) {
        double x = (i + 1) * 100.0;
        os << "G1 X" << x << " Y0 E" << (0.05 * 100.0) << " F3000\n";
        // Add a dwell after every segment (including consecutive)
        os << "G4 P" << (100 + i * 50) << " ; dwell\n";
        numDwells++;
    }

    auto result = runDwellPipeline(os.str());
    ASSERT_NE(result.wss, nullptr)
        << "Planner returned null for " << numDwells << " dwells";
    ASSERT_EQ(result.dwellPoints.size(), static_cast<size_t>(numDwells));

    const auto& arcs = result.wss->arcs();
    ASSERT_GT(arcs.size(), static_cast<size_t>(numDwells));

    // Count DWELL arcs
    int dwellArcCount = 0;
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) {
            dwellArcCount++;
            EXPECT_NEAR(arc.v0, 0.0, 1e-10);
            EXPECT_NEAR(arc.a0, 0.0, 1e-10);
            EXPECT_NEAR(arc.s1 - arc.s0, 0.0, 1e-10);
        }
    }
    EXPECT_EQ(dwellArcCount, numDwells);

    // Start/end velocity = 0
    EXPECT_NEAR(arcs.front().v0, 0.0, 1e-3);
    EXPECT_NEAR(arcEndVelocity(arcs.back()), 0.0, 1e-3);

    // Total time includes all dwell durations
    double totalDwellTime = 0.0;
    for (const auto& dp : result.dwellPoints) {
        totalDwellTime += dp.duration;
    }
    EXPECT_GT(result.wss->totalTime(), totalDwellTime);

    std::cout << "Dwell_ManyDwells summary:\n"
              << "  Segments: " << numSegments << "\n"
              << "  DWELL arcs: " << dwellArcCount << "\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  Total time: " << result.wss->totalTime() << " s\n"
              << "  Total dwell time: " << totalDwellTime << " s\n";
}

// ===========================================================================
// Dwell infeasibility tests
//
// These tests verify that the planner gracefully handles edge cases where
// dwell points create challenging or infeasible configurations. The planner
// should either:
//   - Return a valid WSS with correct DWELL arcs (when feasible), or
//   - Return nullptr (when truly infeasible)
//
// In no case should the planner crash, hang, or produce invalid arcs.
// ===========================================================================

TEST(RoundedSquareGCodeTest, Dwell_Infeasible_DwellAtStartOfPath) {
    // Dwell at the very start of the path (s=0). The planner should handle
    // this gracefully — the first sub-path has zero length, so only a DWELL
    // arc is produced, followed by the rest of the path.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    os << "G4 P500 ; dwell at start\n";
    os << "G1 X100 Y0 E5 F3000\n";
    os << "G1 X200 Y0 E5 F3000\n";

    auto result = runDwellPipeline(os.str());
    ASSERT_NE(result.wss, nullptr)
        << "Planner should handle dwell at path start";
    ASSERT_EQ(result.dwellPoints.size(), 1u);

    const auto& arcs = result.wss->arcs();
    ASSERT_GT(arcs.size(), 1u);

    // The first arc should be a DWELL arc at s=0
    EXPECT_EQ(arcs.front().type, WeightedArcType::DWELL);
    EXPECT_NEAR(arcs.front().s0, 0.0, 1e-6);
    EXPECT_NEAR(arcs.front().duration, 0.5, 1e-6);

    // End velocity = 0
    EXPECT_NEAR(arcEndVelocity(arcs.back()), 0.0, 1e-3);

    std::cout << "Dwell_Infeasible_DwellAtStart summary:\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  Total time: " << result.wss->totalTime() << " s\n";
}

TEST(RoundedSquareGCodeTest, Dwell_Infeasible_DwellAtEndOfPath) {
    // Dwell at the very end of the path. The last sub-path has zero length,
    // so only a DWELL arc is produced at the end.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    os << "G1 X100 Y0 E5 F3000\n";
    os << "G1 X200 Y0 E5 F3000\n";
    os << "G4 P750 ; dwell at end\n";

    auto result = runDwellPipeline(os.str());
    ASSERT_NE(result.wss, nullptr)
        << "Planner should handle dwell at path end";
    ASSERT_EQ(result.dwellPoints.size(), 1u);

    const auto& arcs = result.wss->arcs();
    ASSERT_GT(arcs.size(), 1u);

    // The last arc should be a DWELL arc
    EXPECT_EQ(arcs.back().type, WeightedArcType::DWELL);
    EXPECT_NEAR(arcs.back().duration, 0.75, 1e-6);

    // Start velocity = 0
    EXPECT_NEAR(arcs.front().v0, 0.0, 1e-3);

    std::cout << "Dwell_Infeasible_DwellAtEnd summary:\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  Total time: " << result.wss->totalTime() << " s\n";
}

TEST(RoundedSquareGCodeTest, Dwell_Infeasible_DwellAtStartAndEnd) {
    // Dwells at both the start and end of the path.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    os << "G4 P100 ; dwell at start\n";
    os << "G1 X100 Y0 E5 F3000\n";
    os << "G4 P200 ; dwell in middle\n";
    os << "G1 X200 Y0 E5 F3000\n";
    os << "G4 P300 ; dwell at end\n";

    auto result = runDwellPipeline(os.str());
    ASSERT_NE(result.wss, nullptr)
        << "Planner should handle dwells at start and end";
    ASSERT_EQ(result.dwellPoints.size(), 3u);

    const auto& arcs = result.wss->arcs();
    ASSERT_GT(arcs.size(), 3u);

    // First arc should be a DWELL
    EXPECT_EQ(arcs.front().type, WeightedArcType::DWELL);
    EXPECT_NEAR(arcs.front().duration, 0.1, 1e-6);

    // Last arc should be a DWELL
    EXPECT_EQ(arcs.back().type, WeightedArcType::DWELL);
    EXPECT_NEAR(arcs.back().duration, 0.3, 1e-6);

    // Count DWELL arcs
    int dwellArcCount = 0;
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) dwellArcCount++;
    }
    EXPECT_EQ(dwellArcCount, 3);

    std::cout << "Dwell_Infeasible_DwellAtStartAndEnd summary:\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  DWELL arcs: " << dwellArcCount << "\n"
              << "  Total time: " << result.wss->totalTime() << " s\n";
}

TEST(RoundedSquareGCodeTest, Dwell_Infeasible_ZeroDurationDwell) {
    // A dwell with zero duration (G4 P0). This is a no-op dwell.
    // The planner should handle it gracefully — the DWELL arc has
    // duration 0, and the path is effectively unsplit.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    os << "G1 X100 Y0 E5 F3000\n";
    os << "G4 P0 ; zero-duration dwell\n";
    os << "G1 X200 Y0 E5 F3000\n";

    auto result = runDwellPipeline(os.str());
    // The planner should still produce a valid result.
    // A zero-duration dwell creates a zero-length sub-path split,
    // but the DWELL arc itself has duration 0.
    if (result.wss) {
        const auto& arcs = result.wss->arcs();
        int dwellArcCount = 0;
        for (const auto& arc : arcs) {
            if (arc.type == WeightedArcType::DWELL) {
                dwellArcCount++;
                EXPECT_NEAR(arc.duration, 0.0, 1e-10);
            }
        }
        EXPECT_EQ(dwellArcCount, 1);
        EXPECT_NEAR(arcs.front().v0, 0.0, 1e-3);
        EXPECT_NEAR(arcEndVelocity(arcs.back()), 0.0, 1e-3);

        std::cout << "Dwell_Infeasible_ZeroDurationDwell summary:\n"
                  << "  WSS arcs: " << arcs.size() << "\n"
                  << "  DWELL arcs: " << dwellArcCount << "\n"
                  << "  Total time: " << result.wss->totalTime() << " s\n";
    } else {
        // If the planner returns null, that's also acceptable for a
        // zero-duration dwell (it's a degenerate case).
        std::cout << "Dwell_Infeasible_ZeroDurationDwell: planner returned null "
                     "(acceptable for zero-duration dwell)\n";
    }
}

TEST(RoundedSquareGCodeTest, Dwell_Infeasible_AllDwellsConsecutive) {
    // A path that is entirely dwells with no motion between them.
    // The planner should produce only DWELL arcs with no motion arcs.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    os << "G1 X100 Y0 E5 F3000\n";
    // 5 consecutive dwells at the same position
    os << "G4 P100\n";
    os << "G4 P200\n";
    os << "G4 P300\n";
    os << "G4 P400\n";
    os << "G4 P500\n";
    os << "G1 X200 Y0 E5 F3000\n";

    auto result = runDwellPipeline(os.str());
    ASSERT_NE(result.wss, nullptr)
        << "Planner should handle all-consecutive dwells";
    ASSERT_EQ(result.dwellPoints.size(), 5u);

    const auto& arcs = result.wss->arcs();
    ASSERT_GT(arcs.size(), 5u);

    // Count DWELL arcs
    int dwellArcCount = 0;
    std::vector<double> dwellDurations;
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) {
            dwellArcCount++;
            dwellDurations.push_back(arc.duration);
            EXPECT_NEAR(arc.v0, 0.0, 1e-10);
            EXPECT_NEAR(arc.a0, 0.0, 1e-10);
        }
    }
    EXPECT_EQ(dwellArcCount, 5);

    // Verify each dwell duration is individually tracked
    ASSERT_EQ(dwellDurations.size(), 5u);
    EXPECT_NEAR(dwellDurations[0], 0.1, 1e-6);
    EXPECT_NEAR(dwellDurations[1], 0.2, 1e-6);
    EXPECT_NEAR(dwellDurations[2], 0.3, 1e-6);
    EXPECT_NEAR(dwellDurations[3], 0.4, 1e-6);
    EXPECT_NEAR(dwellDurations[4], 0.5, 1e-6);

    // Total dwell time = 0.1 + 0.2 + 0.3 + 0.4 + 0.5 = 1.5s
    double totalDwellTime = 1.5;
    EXPECT_GT(result.wss->totalTime(), totalDwellTime);

    std::cout << "Dwell_Infeasible_AllDwellsConsecutive summary:\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  DWELL arcs: " << dwellArcCount << "\n"
              << "  Total time: " << result.wss->totalTime() << " s\n";
}

TEST(RoundedSquareGCodeTest, Dwell_Infeasible_OnlyDwellsNoMotion) {
    // A path with only dwells and no motion segments at all (except the
    // initial travel move). This is a degenerate case.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    os << "G4 P100\n";
    os << "G4 P200\n";

    // The path has zero length (only a travel move to X0 Y0 and dwells).
    // The NURBS converter may throw or return an empty path.
    // The planner may return null or a valid WSS with only DWELL arcs.
    // In no case should the test crash.
    auto result = runDwellPipeline(os.str());
    if (result.wss) {
        const auto& arcs = result.wss->arcs();
        int dwellArcCount = 0;
        for (const auto& arc : arcs) {
            if (arc.type == WeightedArcType::DWELL) dwellArcCount++;
        }
        std::cout << "Dwell_Infeasible_OnlyDwellsNoMotion summary:\n"
                  << "  WSS arcs: " << arcs.size() << "\n"
                  << "  DWELL arcs: " << dwellArcCount << "\n";
    } else {
        // Returning null is acceptable for a degenerate path with no motion.
        std::cout << "Dwell_Infeasible_OnlyDwellsNoMotion: planner returned null "
                     "(acceptable for no-motion path)\n";
    }
}

TEST(RoundedSquareGCodeTest, Dwell_Infeasible_DwellOnVeryShortSegment) {
    // A dwell on a very short segment (1mm). The planner must be able to
    // decelerate from cruise to v=0 and accelerate back within 1mm.
    // With a_max = 2000 mm/s², the distance to decelerate from 50 mm/s
    // to 0 is v²/(2*a) = 2500/4000 = 0.625 mm, so 1mm is feasible.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    os << "G1 X50 Y0 E2.5 F3000\n";
    os << "G1 X51 Y0 E0.05 F3000\n";  // 1mm segment
    os << "G4 P100 ; dwell on short segment\n";
    os << "G1 X100 Y0 E2.45 F3000\n";

    auto result = runDwellPipeline(os.str());
    ASSERT_NE(result.wss, nullptr)
        << "Planner should handle dwell on very short segment";
    ASSERT_EQ(result.dwellPoints.size(), 1u);

    const auto& arcs = result.wss->arcs();
    ASSERT_GT(arcs.size(), 1u);

    int dwellArcCount = 0;
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) {
            dwellArcCount++;
            EXPECT_NEAR(arc.v0, 0.0, 1e-10);
            EXPECT_NEAR(arc.duration, 0.1, 1e-6);
        }
    }
    EXPECT_EQ(dwellArcCount, 1);

    // Start/end velocity = 0
    EXPECT_NEAR(arcs.front().v0, 0.0, 1e-3);
    EXPECT_NEAR(arcEndVelocity(arcs.back()), 0.0, 1e-3);

    std::cout << "Dwell_Infeasible_DwellOnVeryShortSegment summary:\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  Total time: " << result.wss->totalTime() << " s\n";
}

TEST(RoundedSquareGCodeTest, Dwell_Infeasible_DwellBetweenTwoShortSegments) {
    // A dwell between two very short segments (0.5mm each). The planner
    // must decelerate to v=0 and accelerate back within 0.5mm on each side.
    // With a_max = 2000 mm/s², the distance to decelerate from v to 0
    // is v²/(2*a). For v=20 mm/s, that's 400/4000 = 0.1mm, feasible.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    os << "G1 X50 Y0 E2.5 F3000\n";
    os << "G1 X50.5 Y0 E0.025 F3000\n";  // 0.5mm segment
    os << "G4 P100 ; dwell\n";
    os << "G1 X51 Y0 E0.025 F3000\n";   // 0.5mm segment
    os << "G1 X100 Y0 E2.45 F3000\n";

    auto result = runDwellPipeline(os.str());
    // This may or may not be feasible depending on the solver's ability
    // to handle very short segments with v=0 constraints. We test that
    // the planner doesn't crash.
    if (result.wss) {
        const auto& arcs = result.wss->arcs();
        int dwellArcCount = 0;
        for (const auto& arc : arcs) {
            if (arc.type == WeightedArcType::DWELL) dwellArcCount++;
        }
        EXPECT_EQ(dwellArcCount, 1);
        EXPECT_NEAR(arcs.front().v0, 0.0, 1e-3);
        EXPECT_NEAR(arcEndVelocity(arcs.back()), 0.0, 1e-3);

        std::cout << "Dwell_Infeasible_DwellBetweenTwoShortSegments summary:\n"
                  << "  WSS arcs: " << arcs.size() << "\n"
                  << "  Total time: " << result.wss->totalTime() << " s\n";
    } else {
        // Returning null is acceptable if the segments are too short
        // for the solver to find a feasible trajectory.
        std::cout << "Dwell_Infeasible_DwellBetweenTwoShortSegments: "
                     "planner returned null (acceptable for very short segments)\n";
    }
}

TEST(RoundedSquareGCodeTest, Dwell_Infeasible_LargeNumberOfDwells) {
    // Stress test: 50 dwells on a long path. The planner should handle
    // this without running out of memory or taking excessive time.
    std::ostringstream os;
    os << "G21\nG90\nG92 E0\nG0 X0 Y0 F18000\n";
    int numDwells = 0;
    for (int i = 0; i < 50; ++i) {
        double x = (i + 1) * 20.0;
        os << "G1 X" << x << " Y0 E" << (0.05 * 20.0) << " F3000\n";
        os << "G4 P50 ; dwell\n";
        numDwells++;
    }

    auto result = runDwellPipeline(os.str());
    ASSERT_NE(result.wss, nullptr)
        << "Planner should handle " << numDwells << " dwells";
    ASSERT_EQ(result.dwellPoints.size(), static_cast<size_t>(numDwells));

    const auto& arcs = result.wss->arcs();
    ASSERT_GT(arcs.size(), static_cast<size_t>(numDwells));

    int dwellArcCount = 0;
    for (const auto& arc : arcs) {
        if (arc.type == WeightedArcType::DWELL) {
            dwellArcCount++;
            EXPECT_NEAR(arc.v0, 0.0, 1e-10);
            EXPECT_NEAR(arc.duration, 0.05, 1e-6);
        }
    }
    EXPECT_EQ(dwellArcCount, numDwells);

    // Start/end velocity = 0
    EXPECT_NEAR(arcs.front().v0, 0.0, 1e-3);
    EXPECT_NEAR(arcEndVelocity(arcs.back()), 0.0, 1e-3);

    std::cout << "Dwell_Infeasible_LargeNumberOfDwells summary:\n"
              << "  DWELL arcs: " << dwellArcCount << "\n"
              << "  WSS arcs: " << arcs.size() << "\n"
              << "  Total time: " << result.wss->totalTime() << " s\n";
}
